<?php
return array(
  array('id' => '1','municipality' => 'Fungling','type' => 'Municipality','district' => 'Taplejung','state' => '1'),
  array('id' => '2','municipality' => 'Athrai Tribeni','type' => 'Rural Municipality','district' => 'Taplejung','state' => '1'),
  array('id' => '3','municipality' => 'Sidingwa','type' => 'Rural Municipality','district' => 'Taplejung','state' => '1'),
  array('id' => '4','municipality' => 'Faktanglung','type' => 'Rural Municipality','district' => 'Taplejung','state' => '1'),
  array('id' => '5','municipality' => 'Mikhwakhola','type' => 'Rural Municipality','district' => 'Taplejung','state' => '1'),
  array('id' => '6','municipality' => 'Meringden','type' => 'Rural Municipality','district' => 'Taplejung','state' => '1'),
  array('id' => '7','municipality' => 'Maiwakhola','type' => 'Rural Municipality','district' => 'Taplejung','state' => '1'),
  array('id' => '8','municipality' => 'Yangwarak Taplejung','type' => 'Rural Municipality','district' => 'Taplejung','state' => '1'),
  array('id' => '9','municipality' => 'Sirijunga','type' => 'Rural Municipality','district' => 'Taplejung','state' => '1'),
  array('id' => '10','municipality' => 'Fidim','type' => 'Municipality','district' => 'Panchther','state' => '1'),
  array('id' => '11','municipality' => 'Falelung','type' => 'Rural Municipality','district' => 'Panchther','state' => '1'),
  array('id' => '12','municipality' => 'Falgunanda','type' => 'Rural Municipality','district' => 'Panchther','state' => '1'),
  array('id' => '13','municipality' => 'Hilihang','type' => 'Rural Municipality','district' => 'Panchther','state' => '1'),
  array('id' => '14','municipality' => 'Kummayek','type' => 'Rural Municipality','district' => 'Panchther','state' => '1'),
  array('id' => '15','municipality' => 'Miklajung Panchther','type' => 'Rural Municipality','district' => 'Panchther','state' => '1'),
  array('id' => '16','municipality' => 'Tumwewa','type' => 'Rural Municipality','district' => 'Panchther','state' => '1'),
  array('id' => '17','municipality' => 'Yangwarak Panchther','type' => 'Rural Municipality','district' => 'Panchther','state' => '1'),
  array('id' => '18','municipality' => 'Illam','type' => 'Municipality','district' => 'Illam','state' => '1'),
  array('id' => '19','municipality' => 'Deumai','type' => 'Municipality','district' => 'Illam','state' => '1'),
  array('id' => '20','municipality' => 'Mai','type' => 'Municipality','district' => 'Illam','state' => '1'),
  array('id' => '21','municipality' => 'Suryodaya','type' => 'Municipality','district' => 'Illam','state' => '1'),
  array('id' => '22','municipality' => 'Fakfokthum','type' => 'Rural Municipality','district' => 'Illam','state' => '1'),
  array('id' => '23','municipality' => 'Chulachuli','type' => 'Rural Municipality','district' => 'Illam','state' => '1'),
  array('id' => '24','municipality' => 'Maijogmai','type' => 'Rural Municipality','district' => 'Illam','state' => '1'),
  array('id' => '25','municipality' => 'Mangsebung','type' => 'Rural Municipality','district' => 'Illam','state' => '1'),
  array('id' => '26','municipality' => 'Rong','type' => 'Rural Municipality','district' => 'Illam','state' => '1'),
  array('id' => '27','municipality' => 'Sandakpur','type' => 'Rural Municipality','district' => 'Illam','state' => '1'),
  array('id' => '28','municipality' => 'Mechinagar','type' => 'Municipality','district' => 'Jhapa','state' => '1'),
  array('id' => '29','municipality' => 'Damak','type' => 'Municipality','district' => 'Jhapa','state' => '1'),
  array('id' => '30','municipality' => 'Kankai','type' => 'Municipality','district' => 'Jhapa','state' => '1'),
  array('id' => '31','municipality' => 'Bhadrapur','type' => 'Municipality','district' => 'Jhapa','state' => '1'),
  array('id' => '32','municipality' => 'Arjundhara','type' => 'Municipality','district' => 'Jhapa','state' => '1'),
  array('id' => '33','municipality' => 'Shivasatakshi','type' => 'Municipality','district' => 'Jhapa','state' => '1'),
  array('id' => '34','municipality' => 'Gauradaha','type' => 'Municipality','district' => 'Jhapa','state' => '1'),
  array('id' => '35','municipality' => 'Birtamod','type' => 'Municipality','district' => 'Jhapa','state' => '1'),
  array('id' => '36','municipality' => 'Kamal','type' => 'Rural Municipality','district' => 'Jhapa','state' => '1'),
  array('id' => '37','municipality' => 'Gaurigunj','type' => 'Rural Municipality','district' => 'Jhapa','state' => '1'),
  array('id' => '38','municipality' => 'Barhadashi','type' => 'Rural Municipality','district' => 'Jhapa','state' => '1'),
  array('id' => '39','municipality' => 'Jhapa','type' => 'Rural Municipality','district' => 'Jhapa','state' => '1'),
  array('id' => '40','municipality' => 'Buddhasanti','type' => 'Rural Municipality','district' => 'Jhapa','state' => '1'),
  array('id' => '41','municipality' => 'Haldibari','type' => 'Rural Municipality','district' => 'Jhapa','state' => '1'),
  array('id' => '42','municipality' => 'Kachankawal','type' => 'Rural Municipality','district' => 'Jhapa','state' => '1'),
  array('id' => '43','municipality' => 'Biratnagar','type' => 'MetroPolitan City','district' => 'Morang','state' => '1'),
  array('id' => '44','municipality' => 'Belbaari','type' => 'Municipality','district' => 'Morang','state' => '1'),
  array('id' => '45','municipality' => 'Letang','type' => 'Municipality','district' => 'Morang','state' => '1'),
  array('id' => '46','municipality' => 'Pathari Sanischare','type' => 'Municipality','district' => 'Morang','state' => '1'),
  array('id' => '47','municipality' => 'Rangeli','type' => 'Municipality','district' => 'Morang','state' => '1'),
  array('id' => '48','municipality' => 'Ratuwamai','type' => 'Municipality','district' => 'Morang','state' => '1'),
  array('id' => '49','municipality' => 'Sunawarsi','type' => 'Municipality','district' => 'Morang','state' => '1'),
  array('id' => '50','municipality' => 'Urlabaari','type' => 'Municipality','district' => 'Morang','state' => '1'),
  array('id' => '51','municipality' => 'Sundarharaincha','type' => 'Municipality','district' => 'Morang','state' => '1'),
  array('id' => '52','municipality' => 'Budhiganga Morang','type' => 'Rural Municipality','district' => 'Morang','state' => '1'),
  array('id' => '53','municipality' => 'Dhanpalthan','type' => 'Rural Municipality','district' => 'Morang','state' => '1'),
  array('id' => '54','municipality' => 'Gramthan','type' => 'Rural Municipality','district' => 'Morang','state' => '1'),
  array('id' => '55','municipality' => 'Jahada','type' => 'Rural Municipality','district' => 'Morang','state' => '1'),
  array('id' => '56','municipality' => 'Kanepokhari','type' => 'Rural Municipality','district' => 'Morang','state' => '1'),
  array('id' => '57','municipality' => 'Katahari','type' => 'Rural Municipality','district' => 'Morang','state' => '1'),
  array('id' => '58','municipality' => 'Kerabaari','type' => 'Rural Municipality','district' => 'Morang','state' => '1'),
  array('id' => '59','municipality' => 'Miklajung Morang','type' => 'Rural Municipality','district' => 'Morang','state' => '1'),
  array('id' => '60','municipality' => 'Itahari','type' => 'Sub Metropolitan City','district' => 'Sunsari','state' => '1'),
  array('id' => '61','municipality' => 'Dharan','type' => 'Sub Metropolitan City','district' => 'Sunsari','state' => '1'),
  array('id' => '62','municipality' => 'Inaruwa','type' => 'Municipality','district' => 'Sunsari','state' => '1'),
  array('id' => '63','municipality' => 'Duhabi','type' => 'Municipality','district' => 'Sunsari','state' => '1'),
  array('id' => '64','municipality' => 'Ramdhuni','type' => 'Municipality','district' => 'Sunsari','state' => '1'),
  array('id' => '65','municipality' => 'Barah','type' => 'Municipality','district' => 'Sunsari','state' => '1'),
  array('id' => '66','municipality' => 'Dewangunj','type' => 'Rural Municipality','district' => 'Sunsari','state' => '1'),
  array('id' => '67','municipality' => 'Koshi','type' => 'Rural Municipality','district' => 'Sunsari','state' => '1'),
  array('id' => '68','municipality' => 'Gadhi','type' => 'Rural Municipality','district' => 'Sunsari','state' => '1'),
  array('id' => '69','municipality' => 'Barju','type' => 'Rural Municipality','district' => 'Sunsari','state' => '1'),
  array('id' => '70','municipality' => 'Bhokraha','type' => 'Rural Municipality','district' => 'Sunsari','state' => '1'),
  array('id' => '71','municipality' => 'Harinagara','type' => 'Rural Municipality','district' => 'Sunsari','state' => '1'),
  array('id' => '72','municipality' => 'Pakhribaas','type' => 'Municipality','district' => 'Dhankuta','state' => '1'),
  array('id' => '73','municipality' => 'Dhankuta','type' => 'Municipality','district' => 'Dhankuta','state' => '1'),
  array('id' => '74','municipality' => 'Mahalaxmi Dhankuta','type' => 'Municipality','district' => 'Dhankuta','state' => '1'),
  array('id' => '75','municipality' => 'Sagurigadhi','type' => 'Rural Municipality','district' => 'Dhankuta','state' => '1'),
  array('id' => '76','municipality' => 'Khalsa Chhintang Sahidbhumi','type' => 'Rural Municipality','district' => 'Dhankuta','state' => '1'),
  array('id' => '77','municipality' => 'Chhathar Jorpati','type' => 'Rural Municipality','district' => 'Dhankuta','state' => '1'),
  array('id' => '78','municipality' => 'Chaubise','type' => 'Rural Municipality','district' => 'Dhankuta','state' => '1'),
  array('id' => '79','municipality' => 'Myanglung','type' => 'Municipality','district' => 'Terhathum','state' => '1'),
  array('id' => '80','municipality' => 'Laligurans','type' => 'Municipality','district' => 'Terhathum','state' => '1'),
  array('id' => '81','municipality' => 'Athrai','type' => 'Rural Municipality','district' => 'Terhathum','state' => '1'),
  array('id' => '82','municipality' => 'Chhathar','type' => 'Rural Municipality','district' => 'Terhathum','state' => '1'),
  array('id' => '83','municipality' => 'Fedaap','type' => 'Rural Municipality','district' => 'Terhathum','state' => '1'),
  array('id' => '84','municipality' => 'Menchhayayem','type' => 'Rural Municipality','district' => 'Terhathum','state' => '1'),
  array('id' => '85','municipality' => 'Chainpur','type' => 'Municipality','district' => 'Sankhuwasabha','state' => '1'),
  array('id' => '86','municipality' => 'Dharmadevi','type' => 'Municipality','district' => 'Sankhuwasabha','state' => '1'),
  array('id' => '87','municipality' => 'Khaadbaari','type' => 'Municipality','district' => 'Sankhuwasabha','state' => '1'),
  array('id' => '88','municipality' => 'Madi Sankhuwasabha','type' => 'Municipality','district' => 'Sankhuwasabha','state' => '1'),
  array('id' => '89','municipality' => 'Paanchkhapan','type' => 'Municipality','district' => 'Sankhuwasabha','state' => '1'),
  array('id' => '90','municipality' => 'Bhotkhola','type' => 'Rural Municipality','district' => 'Sankhuwasabha','state' => '1'),
  array('id' => '91','municipality' => 'Chichila','type' => 'Rural Municipality','district' => 'Sankhuwasabha','state' => '1'),
  array('id' => '92','municipality' => 'Makalu','type' => 'Rural Municipality','district' => 'Sankhuwasabha','state' => '1'),
  array('id' => '93','municipality' => 'Sabhapokhari','type' => 'Rural Municipality','district' => 'Sankhuwasabha','state' => '1'),
  array('id' => '94','municipality' => 'Silichong','type' => 'Rural Municipality','district' => 'Sankhuwasabha','state' => '1'),
  array('id' => '95','municipality' => 'Bhojpur','type' => 'Municipality','district' => 'Bhojpur','state' => '1'),
  array('id' => '96','municipality' => 'Sadananda','type' => 'Municipality','district' => 'Bhojpur','state' => '1'),
  array('id' => '97','municipality' => 'Tyamkemaiyum','type' => 'Rural Municipality','district' => 'Bhojpur','state' => '1'),
  array('id' => '98','municipality' => 'Ramprasadrai','type' => 'Rural Municipality','district' => 'Bhojpur','state' => '1'),
  array('id' => '99','municipality' => 'Arun','type' => 'Rural Municipality','district' => 'Bhojpur','state' => '1'),
  array('id' => '100','municipality' => 'Pauwadungma','type' => 'Rural Municipality','district' => 'Bhojpur','state' => '1'),
  array('id' => '101','municipality' => 'Salpasilichho','type' => 'Rural Municipality','district' => 'Bhojpur','state' => '1'),
  array('id' => '102','municipality' => 'Aamchowk','type' => 'Rural Municipality','district' => 'Bhojpur','state' => '1'),
  array('id' => '103','municipality' => 'Hatuwagadhi','type' => 'Rural Municipality','district' => 'Bhojpur','state' => '1'),
  array('id' => '104','municipality' => 'Solududhkunda','type' => 'Municipality','district' => 'Solukhumbu','state' => '1'),
  array('id' => '105','municipality' => 'Dudhkoshi','type' => 'Rural Municipality','district' => 'Solukhumbu','state' => '1'),
  array('id' => '106','municipality' => 'Khumbu Pasang Lhamu','type' => 'Rural Municipality','district' => 'Solukhumbu','state' => '1'),
  array('id' => '107','municipality' => 'Dudhkausika','type' => 'Rural Municipality','district' => 'Solukhumbu','state' => '1'),
  array('id' => '108','municipality' => 'Nechasalyan','type' => 'Rural Municipality','district' => 'Solukhumbu','state' => '1'),
  array('id' => '109','municipality' => 'Mahakulung','type' => 'Rural Municipality','district' => 'Solukhumbu','state' => '1'),
  array('id' => '110','municipality' => 'Likhu Pike','type' => 'Rural Municipality','district' => 'Solukhumbu','state' => '1'),
  array('id' => '111','municipality' => 'Sotang','type' => 'Rural Municipality','district' => 'Solukhumbu','state' => '1'),
  array('id' => '112','municipality' => 'Siddhicharan','type' => 'Municipality','district' => 'Okhaldhunga','state' => '1'),
  array('id' => '113','municipality' => 'Khijidemwa','type' => 'Rural Municipality','district' => 'Okhaldhunga','state' => '1'),
  array('id' => '114','municipality' => 'Champadevi','type' => 'Rural Municipality','district' => 'Okhaldhunga','state' => '1'),
  array('id' => '115','municipality' => 'Chisankhugadhi','type' => 'Rural Municipality','district' => 'Okhaldhunga','state' => '1'),
  array('id' => '116','municipality' => 'Manebhanjyang','type' => 'Rural Municipality','district' => 'Okhaldhunga','state' => '1'),
  array('id' => '117','municipality' => 'Molung','type' => 'Rural Municipality','district' => 'Okhaldhunga','state' => '1'),
  array('id' => '118','municipality' => 'Likhu Okhaldhunga','type' => 'Rural Municipality','district' => 'Okhaldhunga','state' => '1'),
  array('id' => '119','municipality' => 'Sunkoshi Okhaldhunga','type' => 'Rural Municipality','district' => 'Okhaldhunga','state' => '1'),
  array('id' => '120','municipality' => 'Halesituwachung','type' => 'Municipality','district' => 'Khotang','state' => '1'),
  array('id' => '121','municipality' => 'Rupakot Majhuwagadhi','type' => 'Municipality','district' => 'Khotang','state' => '1'),
  array('id' => '122','municipality' => 'Aiselukharka','type' => 'Rural Municipality','district' => 'Khotang','state' => '1'),
  array('id' => '123','municipality' => 'Lamidada','type' => 'Rural Municipality','district' => 'Khotang','state' => '1'),
  array('id' => '124','municipality' => 'Jantedhunga','type' => 'Rural Municipality','district' => 'Khotang','state' => '1'),
  array('id' => '125','municipality' => 'Khotehang','type' => 'Rural Municipality','district' => 'Khotang','state' => '1'),
  array('id' => '126','municipality' => 'Kepilasgadhi','type' => 'Rural Municipality','district' => 'Khotang','state' => '1'),
  array('id' => '127','municipality' => 'Diprung','type' => 'Rural Municipality','district' => 'Khotang','state' => '1'),
  array('id' => '128','municipality' => 'Sakela','type' => 'Rural Municipality','district' => 'Khotang','state' => '1'),
  array('id' => '129','municipality' => 'Barahpokhari','type' => 'Rural Municipality','district' => 'Khotang','state' => '1'),
  array('id' => '130','municipality' => 'Katari','type' => 'Municipality','district' => 'Udaypur','state' => '1'),
  array('id' => '131','municipality' => 'Chaudandagadhi','type' => 'Municipality','district' => 'Udaypur','state' => '1'),
  array('id' => '132','municipality' => 'Triyuga','type' => 'Municipality','district' => 'Udaypur','state' => '1'),
  array('id' => '133','municipality' => 'Belaka','type' => 'Municipality','district' => 'Udaypur','state' => '1'),
  array('id' => '134','municipality' => 'Udaypurgadhi','type' => 'Rural Municipality','district' => 'Udaypur','state' => '1'),
  array('id' => '135','municipality' => 'Tapli','type' => 'Rural Municipality','district' => 'Udaypur','state' => '1'),
  array('id' => '136','municipality' => 'Rautamai','type' => 'Rural Municipality','district' => 'Udaypur','state' => '1'),
  array('id' => '137','municipality' => 'Sunkoshi Udaypur','type' => 'Rural Municipality','district' => 'Udaypur','state' => '1'),
  array('id' => '138','municipality' => 'rajbiraj','type' => 'Municipality','district' => 'Saptari','state' => '2'),
  array('id' => '139','municipality' => 'Kanchanrup','type' => 'Municipality','district' => 'Saptari','state' => '2'),
  array('id' => '140','municipality' => 'Dakneshwori','type' => 'Municipality','district' => 'Saptari','state' => '2'),
  array('id' => '141','municipality' => 'Bodebarsain','type' => 'Municipality','district' => 'Saptari','state' => '2'),
  array('id' => '142','municipality' => 'Khadak','type' => 'Municipality','district' => 'Saptari','state' => '2'),
  array('id' => '143','municipality' => 'Sambhunath','type' => 'Municipality','district' => 'Saptari','state' => '2'),
  array('id' => '144','municipality' => 'Surunga','type' => 'Municipality','district' => 'Saptari','state' => '2'),
  array('id' => '145','municipality' => 'hanumannagar kankalini','type' => 'Municipality','district' => 'Saptari','state' => '2'),
  array('id' => '146','municipality' => 'Saptakosi','type' => 'Municipality','district' => 'Saptari','state' => '2'),
  array('id' => '147','municipality' => 'Agnisair Krishnasawaran','type' => 'Rural Municipality','district' => 'Saptari','state' => '2'),
  array('id' => '148','municipality' => 'Chhinnamasta','type' => 'Rural Municipality','district' => 'Saptari','state' => '2'),
  array('id' => '149','municipality' => 'Mahadeva','type' => 'Rural Municipality','district' => 'Saptari','state' => '2'),
  array('id' => '150','municipality' => 'Tirahut','type' => 'Rural Municipality','district' => 'Saptari','state' => '2'),
  array('id' => '151','municipality' => 'Tilathi Koiladi','type' => 'Rural Municipality','district' => 'Saptari','state' => '2'),
  array('id' => '152','municipality' => 'Rupani','type' => 'Rural Municipality','district' => 'Saptari','state' => '2'),
  array('id' => '153','municipality' => 'Belhi Chapena','type' => 'Rural Municipality','district' => 'Saptari','state' => '2'),
  array('id' => '154','municipality' => 'Bishnupur Saptari','type' => 'Rural Municipality','district' => 'Saptari','state' => '2'),
  array('id' => '155','municipality' => 'Balan Bihul','type' => 'Rural Municipality','district' => 'Saptari','state' => '2'),
  array('id' => '156','municipality' => 'Lahan','type' => 'Municipality','district' => 'Siraha','state' => '2'),
  array('id' => '157','municipality' => 'Dhangadimai','type' => 'Municipality','district' => 'Siraha','state' => '2'),
  array('id' => '158','municipality' => 'Siraha','type' => 'Municipality','district' => 'Siraha','state' => '2'),
  array('id' => '159','municipality' => 'Golbazar','type' => 'Municipality','district' => 'Siraha','state' => '2'),
  array('id' => '160','municipality' => 'Mirchaiya','type' => 'Municipality','district' => 'Siraha','state' => '2'),
  array('id' => '161','municipality' => 'Kalyanpur','type' => 'Municipality','district' => 'Siraha','state' => '2'),
  array('id' => '162','municipality' => 'Karjanha','type' => 'Municipality','district' => 'Siraha','state' => '2'),
  array('id' => '163','municipality' => 'Sukhipur','type' => 'Municipality','district' => 'Siraha','state' => '2'),
  array('id' => '164','municipality' => 'Bhagawanpur','type' => 'Rural Municipality','district' => 'Siraha','state' => '2'),
  array('id' => '165','municipality' => 'Aurahi Siraha','type' => 'Rural Municipality','district' => 'Siraha','state' => '2'),
  array('id' => '166','municipality' => 'Bishnupur Siraha','type' => 'Rural Municipality','district' => 'Siraha','state' => '2'),
  array('id' => '167','municipality' => 'Bariyarpatti','type' => 'Rural Municipality','district' => 'Siraha','state' => '2'),
  array('id' => '168','municipality' => 'Laxmipur Patari','type' => 'Rural Municipality','district' => 'Siraha','state' => '2'),
  array('id' => '169','municipality' => 'Naraha','type' => 'Rural Municipality','district' => 'Siraha','state' => '2'),
  array('id' => '170','municipality' => 'Sakhuwanankarkatti','type' => 'Rural Municipality','district' => 'Siraha','state' => '2'),
  array('id' => '171','municipality' => 'Arnama','type' => 'Rural Municipality','district' => 'Siraha','state' => '2'),
  array('id' => '172','municipality' => 'Nawarajpur','type' => 'Rural Municipality','district' => 'Siraha','state' => '2'),
  array('id' => '173','municipality' => 'Janakpur','type' => 'Sub Metropolitan City','district' => 'Dhanusha','state' => '2'),
  array('id' => '174','municipality' => 'Chhireshwor','type' => 'Municipality','district' => 'Dhanusha','state' => '2'),
  array('id' => '175','municipality' => 'Ganeshman Charnath','type' => 'Municipality','district' => 'Dhanusha','state' => '2'),
  array('id' => '176','municipality' => 'Dhanusadham','type' => 'Municipality','district' => 'Dhanusha','state' => '2'),
  array('id' => '177','municipality' => 'Nagarain','type' => 'Municipality','district' => 'Dhanusha','state' => '2'),
  array('id' => '178','municipality' => 'Videha','type' => 'Municipality','district' => 'Dhanusha','state' => '2'),
  array('id' => '179','municipality' => 'Mithila','type' => 'Municipality','district' => 'Dhanusha','state' => '2'),
  array('id' => '180','municipality' => 'Sahidnagar','type' => 'Municipality','district' => 'Dhanusha','state' => '2'),
  array('id' => '181','municipality' => 'Sabaila','type' => 'Municipality','district' => 'Dhanusha','state' => '2'),
  array('id' => '182','municipality' => 'Kamala','type' => 'Municipality','district' => 'Dhanusha','state' => '2'),
  array('id' => '183','municipality' => 'Mithila Bihari','type' => 'Municipality','district' => 'Dhanusha','state' => '2'),
  array('id' => '184','municipality' => 'Hansapur','type' => 'Municipality','district' => 'Dhanusha','state' => '2'),
  array('id' => '185','municipality' => 'Janaknandini','type' => 'Rural Municipality','district' => 'Dhanusha','state' => '2'),
  array('id' => '186','municipality' => 'Bateshwor','type' => 'Rural Municipality','district' => 'Dhanusha','state' => '2'),
  array('id' => '187','municipality' => 'Mukhiyapatti musaharmiya','type' => 'Rural Municipality','district' => 'Dhanusha','state' => '2'),
  array('id' => '188','municipality' => 'Laxminiya','type' => 'Rural Municipality','district' => 'Dhanusha','state' => '2'),
  array('id' => '189','municipality' => 'Aurahi Dhanusha','type' => 'Rural Municipality','district' => 'Dhanusha','state' => '2'),
  array('id' => '190','municipality' => 'Dhanauji','type' => 'Rural Municipality','district' => 'Dhanusha','state' => '2'),
  array('id' => '191','municipality' => 'Jaleshwor','type' => 'Municipality','district' => 'Mahottari','state' => '2'),
  array('id' => '192','municipality' => 'Bardibas','type' => 'Municipality','district' => 'Mahottari','state' => '2'),
  array('id' => '193','municipality' => 'Gausala','type' => 'Municipality','district' => 'Mahottari','state' => '2'),
  array('id' => '194','municipality' => 'Loharpatti','type' => 'Municipality','district' => 'Mahottari','state' => '2'),
  array('id' => '195','municipality' => 'Ramgopalpur','type' => 'Municipality','district' => 'Mahottari','state' => '2'),
  array('id' => '196','municipality' => 'Manara Siwasa','type' => 'Municipality','district' => 'Mahottari','state' => '2'),
  array('id' => '197','municipality' => 'Matihani','type' => 'Municipality','district' => 'Mahottari','state' => '2'),
  array('id' => '198','municipality' => 'Bhanggaha','type' => 'Municipality','district' => 'Mahottari','state' => '2'),
  array('id' => '199','municipality' => 'Balawa','type' => 'Municipality','district' => 'Mahottari','state' => '2'),
  array('id' => '200','municipality' => 'Aurahi Mahottari','type' => 'Municipality','district' => 'Mahottari','state' => '2'),
  array('id' => '201','municipality' => 'Ekdara','type' => 'Rural Municipality','district' => 'Mahottari','state' => '2'),
  array('id' => '202','municipality' => 'Sonama','type' => 'Rural Municipality','district' => 'Mahottari','state' => '2'),
  array('id' => '203','municipality' => 'Samsi','type' => 'Rural Municipality','district' => 'Mahottari','state' => '2'),
  array('id' => '204','municipality' => 'Mahottari','type' => 'Rural Municipality','district' => 'Mahottari','state' => '2'),
  array('id' => '205','municipality' => 'Pipara','type' => 'Rural Municipality','district' => 'Mahottari','state' => '2'),
  array('id' => '206','municipality' => 'Ishworpur','type' => 'Municipality','district' => 'Sarlahi','state' => '2'),
  array('id' => '207','municipality' => 'Malangawa','type' => 'Municipality','district' => 'Sarlahi','state' => '2'),
  array('id' => '208','municipality' => 'Lalbandi','type' => 'Municipality','district' => 'Sarlahi','state' => '2'),
  array('id' => '209','municipality' => 'Haripur','type' => 'Municipality','district' => 'Sarlahi','state' => '2'),
  array('id' => '210','municipality' => 'Haripurba','type' => 'Municipality','district' => 'Sarlahi','state' => '2'),
  array('id' => '211','municipality' => 'Hariban','type' => 'Municipality','district' => 'Sarlahi','state' => '2'),
  array('id' => '212','municipality' => 'Barahathawa','type' => 'Municipality','district' => 'Sarlahi','state' => '2'),
  array('id' => '213','municipality' => 'Balara','type' => 'Municipality','district' => 'Sarlahi','state' => '2'),
  array('id' => '214','municipality' => 'Godaita','type' => 'Municipality','district' => 'Sarlahi','state' => '2'),
  array('id' => '215','municipality' => 'Bagmati Mahottari','type' => 'Municipality','district' => 'Sarlahi','state' => '2'),
  array('id' => '216','municipality' => 'Kabilasi','type' => 'Municipality','district' => 'Sarlahi','state' => '2'),
  array('id' => '217','municipality' => 'Chakraghatta','type' => 'Rural Municipality','district' => 'Sarlahi','state' => '2'),
  array('id' => '218','municipality' => 'Chandranagar','type' => 'Rural Municipality','district' => 'Sarlahi','state' => '2'),
  array('id' => '219','municipality' => 'Dhankaul','type' => 'Rural Municipality','district' => 'Sarlahi','state' => '2'),
  array('id' => '220','municipality' => 'Bramhapuri','type' => 'Rural Municipality','district' => 'Sarlahi','state' => '2'),
  array('id' => '221','municipality' => 'Ramnagar','type' => 'Rural Municipality','district' => 'Sarlahi','state' => '2'),
  array('id' => '222','municipality' => 'Bishnu','type' => 'Rural Municipality','district' => 'Sarlahi','state' => '2'),
  array('id' => '223','municipality' => 'Kaudena','type' => 'Rural Municipality','district' => 'Sarlahi','state' => '2'),
  array('id' => '224','municipality' => 'Parsa','type' => 'Rural Municipality','district' => 'Sarlahi','state' => '2'),
  array('id' => '225','municipality' => 'Basbariya','type' => 'Rural Municipality','district' => 'Sarlahi','state' => '2'),
  array('id' => '226','municipality' => 'Kamalamaai','type' => 'Municipality','district' => 'Sindhuli','state' => '3'),
  array('id' => '227','municipality' => 'Dudhauli','type' => 'Municipality','district' => 'Sindhuli','state' => '3'),
  array('id' => '228','municipality' => 'Golanjor','type' => 'Rural Municipality','district' => 'Sindhuli','state' => '3'),
  array('id' => '229','municipality' => 'Ghyankhel','type' => 'Rural Municipality','district' => 'Sindhuli','state' => '3'),
  array('id' => '230','municipality' => 'Tinpatan','type' => 'Rural Municipality','district' => 'Sindhuli','state' => '3'),
  array('id' => '231','municipality' => 'Fikkal','type' => 'Rural Municipality','district' => 'Sindhuli','state' => '3'),
  array('id' => '232','municipality' => 'Marin','type' => 'Rural Municipality','district' => 'Sindhuli','state' => '3'),
  array('id' => '233','municipality' => 'Sunkoshi Sindhuli','type' => 'Rural Municipality','district' => 'Sindhuli','state' => '3'),
  array('id' => '234','municipality' => 'Hariharpurgadhi','type' => 'Rural Municipality','district' => 'Sindhuli','state' => '3'),
  array('id' => '235','municipality' => 'Manthali','type' => 'Municipality','district' => 'Ramechhap','state' => '3'),
  array('id' => '236','municipality' => 'Ramechhap','type' => 'Municipality','district' => 'Ramechhap','state' => '3'),
  array('id' => '237','municipality' => 'Umakunda','type' => 'Rural Municipality','district' => 'Ramechhap','state' => '3'),
  array('id' => '238','municipality' => 'Khandadevi','type' => 'Rural Municipality','district' => 'Ramechhap','state' => '3'),
  array('id' => '239','municipality' => 'Gokulganga','type' => 'Rural Municipality','district' => 'Ramechhap','state' => '3'),
  array('id' => '240','municipality' => 'Doramba','type' => 'Rural Municipality','district' => 'Ramechhap','state' => '3'),
  array('id' => '241','municipality' => 'Likhu Ramechhap','type' => 'Rural Municipality','district' => 'Ramechhap','state' => '3'),
  array('id' => '242','municipality' => 'Sunapati','type' => 'Rural Municipality','district' => 'Ramechhap','state' => '3'),
  array('id' => '243','municipality' => 'Jiri','type' => 'Municipality','district' => 'Dolakha','state' => '3'),
  array('id' => '244','municipality' => 'Bhimeshwor','type' => 'Municipality','district' => 'Dolakha','state' => '3'),
  array('id' => '245','municipality' => 'Kalinchowk','type' => 'Rural Municipality','district' => 'Dolakha','state' => '3'),
  array('id' => '246','municipality' => 'Gaurishankar','type' => 'Rural Municipality','district' => 'Dolakha','state' => '3'),
  array('id' => '247','municipality' => 'Tamakoshi','type' => 'Rural Municipality','district' => 'Dolakha','state' => '3'),
  array('id' => '248','municipality' => 'Melung','type' => 'Rural Municipality','district' => 'Dolakha','state' => '3'),
  array('id' => '249','municipality' => 'Bigu','type' => 'Rural Municipality','district' => 'Dolakha','state' => '3'),
  array('id' => '250','municipality' => 'Baiteshwor','type' => 'Rural Municipality','district' => 'Dolakha','state' => '3'),
  array('id' => '251','municipality' => 'Shailung','type' => 'Rural Municipality','district' => 'Dolakha','state' => '3'),
  array('id' => '252','municipality' => 'Chautara Sangachowkgadhi','type' => 'Municipality','district' => 'Sindhupalchowk','state' => '3'),
  array('id' => '253','municipality' => 'Barabise','type' => 'Municipality','district' => 'Sindhupalchowk','state' => '3'),
  array('id' => '254','municipality' => 'Melamchi','type' => 'Municipality','district' => 'Sindhupalchowk','state' => '3'),
  array('id' => '255','municipality' => 'Indrabati','type' => 'Rural Municipality','district' => 'Sindhupalchowk','state' => '3'),
  array('id' => '256','municipality' => 'Jugal','type' => 'Rural Municipality','district' => 'Sindhupalchowk','state' => '3'),
  array('id' => '257','municipality' => 'Panchpokhari Thanpal','type' => 'Rural Municipality','district' => 'Sindhupalchowk','state' => '3'),
  array('id' => '258','municipality' => 'Balephi','type' => 'Rural Municipality','district' => 'Sindhupalchowk','state' => '3'),
  array('id' => '259','municipality' => 'Botekoshi','type' => 'Rural Municipality','district' => 'Sindhupalchowk','state' => '3'),
  array('id' => '260','municipality' => 'Lisankhu Pakhar','type' => 'Rural Municipality','district' => 'Sindhupalchowk','state' => '3'),
  array('id' => '261','municipality' => 'Sunkoshi Sindhupalchowk','type' => 'Rural Municipality','district' => 'Sindhupalchowk','state' => '3'),
  array('id' => '262','municipality' => 'Helambhu','type' => 'Rural Municipality','district' => 'Sindhupalchowk','state' => '3'),
  array('id' => '263','municipality' => 'Tripurasundari Sindhupalchowk','type' => 'Rural Municipality','district' => 'Sindhupalchowk','state' => '3'),
  array('id' => '264','municipality' => 'Dhulikhel','type' => 'Municipality','district' => 'Kavrepalanchowk','state' => '3'),
  array('id' => '265','municipality' => 'Banepa','type' => 'Municipality','district' => 'Kavrepalanchowk','state' => '3'),
  array('id' => '266','municipality' => 'Panauti','type' => 'Municipality','district' => 'Kavrepalanchowk','state' => '3'),
  array('id' => '267','municipality' => 'Panchkhaal','type' => 'Municipality','district' => 'Kavrepalanchowk','state' => '3'),
  array('id' => '268','municipality' => 'Namobuddha','type' => 'Municipality','district' => 'Kavrepalanchowk','state' => '3'),
  array('id' => '269','municipality' => 'Mandandeupur','type' => 'Municipality','district' => 'Kavrepalanchowk','state' => '3'),
  array('id' => '270','municipality' => 'Khanikhola','type' => 'Rural Municipality','district' => 'Kavrepalanchowk','state' => '3'),
  array('id' => '271','municipality' => 'Chaurideurali','type' => 'Rural Municipality','district' => 'Kavrepalanchowk','state' => '3'),
  array('id' => '272','municipality' => 'Temaal','type' => 'Rural Municipality','district' => 'Kavrepalanchowk','state' => '3'),
  array('id' => '273','municipality' => 'Bethanchowk','type' => 'Rural Municipality','district' => 'Kavrepalanchowk','state' => '3'),
  array('id' => '274','municipality' => 'Bhumlu','type' => 'Rural Municipality','district' => 'Kavrepalanchowk','state' => '3'),
  array('id' => '275','municipality' => 'Mahabharat','type' => 'Rural Municipality','district' => 'Kavrepalanchowk','state' => '3'),
  array('id' => '276','municipality' => 'Roshi','type' => 'Rural Municipality','district' => 'Kavrepalanchowk','state' => '3'),
  array('id' => '277','municipality' => 'Lalitpur','type' => 'MetroPolitan City','district' => 'Lalitpur','state' => '3'),
  array('id' => '278','municipality' => 'Godawari Lalitpur','type' => 'Municipality','district' => 'Lalitpur','state' => '3'),
  array('id' => '279','municipality' => 'Mahalaxmi Lalitpur','type' => 'Municipality','district' => 'Lalitpur','state' => '3'),
  array('id' => '280','municipality' => 'Konjyosom','type' => 'Rural Municipality','district' => 'Lalitpur','state' => '3'),
  array('id' => '281','municipality' => 'Bagmati Lalitpur','type' => 'Rural Municipality','district' => 'Lalitpur','state' => '3'),
  array('id' => '282','municipality' => 'Mahankaal','type' => 'Rural Municipality','district' => 'Lalitpur','state' => '3'),
  array('id' => '283','municipality' => 'Changu Narayan','type' => 'Municipality','district' => 'Bhaktapur','state' => '3'),
  array('id' => '284','municipality' => 'Bhaktapur','type' => 'Municipality','district' => 'Bhaktapur','state' => '3'),
  array('id' => '285','municipality' => 'Madhyepur Thimi','type' => 'Municipality','district' => 'Bhaktapur','state' => '3'),
  array('id' => '286','municipality' => 'Suryebinayak','type' => 'Municipality','district' => 'Bhaktapur','state' => '3'),
  array('id' => '287','municipality' => 'Kathmandu','type' => 'MetroPolitan City','district' => 'Kathmandu','state' => '3'),
  array('id' => '288','municipality' => 'Kageshwori Manohara','type' => 'Municipality','district' => 'Kathmandu','state' => '3'),
  array('id' => '289','municipality' => 'Kirtipur','type' => 'Municipality','district' => 'Kathmandu','state' => '3'),
  array('id' => '290','municipality' => 'Gokarneshwor','type' => 'Municipality','district' => 'Kathmandu','state' => '3'),
  array('id' => '291','municipality' => 'Chandragiri','type' => 'Municipality','district' => 'Kathmandu','state' => '3'),
  array('id' => '292','municipality' => 'Tokha','type' => 'Municipality','district' => 'Kathmandu','state' => '3'),
  array('id' => '293','municipality' => 'Tarkeshwor Kathmandu','type' => 'Municipality','district' => 'Kathmandu','state' => '3'),
  array('id' => '294','municipality' => 'Dakchinkali','type' => 'Municipality','district' => 'Kathmandu','state' => '3'),
  array('id' => '295','municipality' => 'Nagarjun','type' => 'Municipality','district' => 'Kathmandu','state' => '3'),
  array('id' => '296','municipality' => 'Budhanilkantha','type' => 'Municipality','district' => 'Kathmandu','state' => '3'),
  array('id' => '297','municipality' => 'Shankharapur','type' => 'Municipality','district' => 'Kathmandu','state' => '3'),
  array('id' => '298','municipality' => 'Bidur','type' => 'Municipality','district' => 'Nuwakot','state' => '3'),
  array('id' => '299','municipality' => 'Belkotgadhi','type' => 'Municipality','district' => 'Nuwakot','state' => '3'),
  array('id' => '300','municipality' => 'Kakani','type' => 'Rural Municipality','district' => 'Nuwakot','state' => '3'),
  array('id' => '301','municipality' => 'Kispang','type' => 'Rural Municipality','district' => 'Nuwakot','state' => '3'),
  array('id' => '302','municipality' => 'Tadi','type' => 'Rural Municipality','district' => 'Nuwakot','state' => '3'),
  array('id' => '303','municipality' => 'Tarkeshwor Nuwakot','type' => 'Rural Municipality','district' => 'Nuwakot','state' => '3'),
  array('id' => '304','municipality' => 'Dupcheshwor','type' => 'Rural Municipality','district' => 'Nuwakot','state' => '3'),
  array('id' => '305','municipality' => 'Panchakanya','type' => 'Rural Municipality','district' => 'Nuwakot','state' => '3'),
  array('id' => '306','municipality' => 'Likhu Nuwakot','type' => 'Rural Municipality','district' => 'Nuwakot','state' => '3'),
  array('id' => '307','municipality' => 'Meghang','type' => 'Rural Municipality','district' => 'Nuwakot','state' => '3'),
  array('id' => '308','municipality' => 'Shivapuri','type' => 'Rural Municipality','district' => 'Nuwakot','state' => '3'),
  array('id' => '309','municipality' => 'Suryegadhi','type' => 'Rural Municipality','district' => 'Nuwakot','state' => '3'),
  array('id' => '310','municipality' => 'Uttargaya','type' => 'Rural Municipality','district' => 'Rasuwa','state' => '3'),
  array('id' => '311','municipality' => 'Kalika Rasuwa','type' => 'Rural Municipality','district' => 'Rasuwa','state' => '3'),
  array('id' => '312','municipality' => 'Gosainkunda','type' => 'Rural Municipality','district' => 'Rasuwa','state' => '3'),
  array('id' => '313','municipality' => 'Naukunda','type' => 'Rural Municipality','district' => 'Rasuwa','state' => '3'),
  array('id' => '314','municipality' => 'Parbatikunda','type' => 'Rural Municipality','district' => 'Rasuwa','state' => '3'),
  array('id' => '315','municipality' => 'Dhunibenshi','type' => 'Municipality','district' => 'Dhadhing','state' => '3'),
  array('id' => '316','municipality' => 'Nilkantha','type' => 'Municipality','district' => 'Dhadhing','state' => '3'),
  array('id' => '317','municipality' => 'Khaniyabash','type' => 'Rural Municipality','district' => 'Dhadhing','state' => '3'),
  array('id' => '318','municipality' => 'Gajuri','type' => 'Rural Municipality','district' => 'Dhadhing','state' => '3'),
  array('id' => '319','municipality' => 'Galchi','type' => 'Rural Municipality','district' => 'Dhadhing','state' => '3'),
  array('id' => '320','municipality' => 'Gangajamuna','type' => 'Rural Municipality','district' => 'Dhadhing','state' => '3'),
  array('id' => '321','municipality' => 'Jwalamukhi','type' => 'Rural Municipality','district' => 'Dhadhing','state' => '3'),
  array('id' => '322','municipality' => 'Thakre','type' => 'Rural Municipality','district' => 'Dhadhing','state' => '3'),
  array('id' => '323','municipality' => 'Netrabati','type' => 'Rural Municipality','district' => 'Dhadhing','state' => '3'),
  array('id' => '324','municipality' => 'Benighat Rorang','type' => 'Rural Municipality','district' => 'Dhadhing','state' => '3'),
  array('id' => '325','municipality' => 'Rubi Valley','type' => 'Rural Municipality','district' => 'Dhadhing','state' => '3'),
  array('id' => '326','municipality' => 'Sidhlake','type' => 'Rural Municipality','district' => 'Dhadhing','state' => '3'),
  array('id' => '327','municipality' => 'Tripurasundari Dhadhing','type' => 'Rural Municipality','district' => 'Dhadhing','state' => '3'),
  array('id' => '328','municipality' => 'Hetauda','type' => 'Sub Metropolitan City','district' => 'Makwanpur','state' => '3'),
  array('id' => '329','municipality' => 'Thaha','type' => 'Municipality','district' => 'Makwanpur','state' => '3'),
  array('id' => '330','municipality' => 'Indrasarobar','type' => 'Rural Municipality','district' => 'Makwanpur','state' => '3'),
  array('id' => '331','municipality' => 'Kailash','type' => 'Rural Municipality','district' => 'Makwanpur','state' => '3'),
  array('id' => '332','municipality' => 'Bakaiya','type' => 'Rural Municipality','district' => 'Makwanpur','state' => '3'),
  array('id' => '333','municipality' => 'Bagmati Makwanpur','type' => 'Rural Municipality','district' => 'Makwanpur','state' => '3'),
  array('id' => '334','municipality' => 'Bhimfedi','type' => 'Rural Municipality','district' => 'Makwanpur','state' => '3'),
  array('id' => '335','municipality' => 'Makwanpurgadhi','type' => 'Rural Municipality','district' => 'Makwanpur','state' => '3'),
  array('id' => '336','municipality' => 'Manhari','type' => 'Rural Municipality','district' => 'Makwanpur','state' => '3'),
  array('id' => '337','municipality' => 'Raksirang','type' => 'Rural Municipality','district' => 'Makwanpur','state' => '3'),
  array('id' => '338','municipality' => 'Chandrapur','type' => 'Municipality','district' => 'Rautahat','state' => '2'),
  array('id' => '339','municipality' => 'Garuda','type' => 'Municipality','district' => 'Rautahat','state' => '2'),
  array('id' => '340','municipality' => 'Gaur','type' => 'Municipality','district' => 'Rautahat','state' => '2'),
  array('id' => '341','municipality' => 'Baudhimai','type' => 'Municipality','district' => 'Rautahat','state' => '2'),
  array('id' => '342','municipality' => 'Brindaban','type' => 'Municipality','district' => 'Rautahat','state' => '2'),
  array('id' => '343','municipality' => 'Dewahi Gonahi','type' => 'Municipality','district' => 'Rautahat','state' => '2'),
  array('id' => '344','municipality' => 'Gadhimai','type' => 'Municipality','district' => 'Rautahat','state' => '2'),
  array('id' => '345','municipality' => 'Gujara','type' => 'Municipality','district' => 'Rautahat','state' => '2'),
  array('id' => '346','municipality' => 'Katahariya','type' => 'Municipality','district' => 'Rautahat','state' => '2'),
  array('id' => '347','municipality' => 'Madhav Narayan','type' => 'Municipality','district' => 'Rautahat','state' => '2'),
  array('id' => '348','municipality' => 'Maulapur','type' => 'Municipality','district' => 'Rautahat','state' => '2'),
  array('id' => '349','municipality' => 'Fatuwa Bijayapur','type' => 'Municipality','district' => 'Rautahat','state' => '2'),
  array('id' => '350','municipality' => 'Ishanath','type' => 'Municipality','district' => 'Rautahat','state' => '2'),
  array('id' => '351','municipality' => 'Paroha','type' => 'Municipality','district' => 'Rautahat','state' => '2'),
  array('id' => '352','municipality' => 'Rajpur Rautahat','type' => 'Municipality','district' => 'Rautahat','state' => '2'),
  array('id' => '353','municipality' => 'Rajdevi','type' => 'Municipality','district' => 'Rautahat','state' => '2'),
  array('id' => '354','municipality' => 'Durga Bhagawati','type' => 'Rural Municipality','district' => 'Rautahat','state' => '2'),
  array('id' => '355','municipality' => 'Yamunamai','type' => 'Rural Municipality','district' => 'Rautahat','state' => '2'),
  array('id' => '356','municipality' => 'Kalaiya','type' => 'Sub Metropolitan City','district' => 'Bara','state' => '2'),
  array('id' => '357','municipality' => 'Jitpursimara','type' => 'Sub Metropolitan City','district' => 'Bara','state' => '2'),
  array('id' => '358','municipality' => 'Kolhawi','type' => 'Municipality','district' => 'Bara','state' => '2'),
  array('id' => '359','municipality' => 'Nijgadh','type' => 'Municipality','district' => 'Bara','state' => '2'),
  array('id' => '360','municipality' => 'Mahagadimai','type' => 'Municipality','district' => 'Bara','state' => '2'),
  array('id' => '361','municipality' => 'Simraungadh','type' => 'Municipality','district' => 'Bara','state' => '2'),
  array('id' => '362','municipality' => 'Pachrauta','type' => 'Municipality','district' => 'Bara','state' => '2'),
  array('id' => '363','municipality' => 'Adarsha Kotwal','type' => 'Rural Municipality','district' => 'Bara','state' => '2'),
  array('id' => '364','municipality' => 'Karaiyamai','type' => 'Rural Municipality','district' => 'Bara','state' => '2'),
  array('id' => '365','municipality' => 'Devtaal','type' => 'Rural Municipality','district' => 'Bara','state' => '2'),
  array('id' => '366','municipality' => 'Parwanipur','type' => 'Rural Municipality','district' => 'Bara','state' => '2'),
  array('id' => '367','municipality' => 'Prasauni','type' => 'Rural Municipality','district' => 'Bara','state' => '2'),
  array('id' => '368','municipality' => 'Pheta','type' => 'Rural Municipality','district' => 'Bara','state' => '2'),
  array('id' => '369','municipality' => 'Baragadhi','type' => 'Rural Municipality','district' => 'Bara','state' => '2'),
  array('id' => '370','municipality' => 'Subarna','type' => 'Rural Municipality','district' => 'Bara','state' => '2'),
  array('id' => '371','municipality' => 'Bishrampur','type' => 'Rural Municipality','district' => 'Bara','state' => '2'),
  array('id' => '372','municipality' => 'Birgunj','type' => 'MetroPolitan City','district' => 'Parsa','state' => '2'),
  array('id' => '373','municipality' => 'Pokhariya','type' => 'Municipality','district' => 'Parsa','state' => '2'),
  array('id' => '374','municipality' => 'Bahudarmai','type' => 'Municipality','district' => 'Parsa','state' => '2'),
  array('id' => '375','municipality' => 'Parsagadhi','type' => 'Municipality','district' => 'Parsa','state' => '2'),
  array('id' => '376','municipality' => 'Thori','type' => 'Rural Municipality','district' => 'Parsa','state' => '2'),
  array('id' => '377','municipality' => 'Jagarnathpur','type' => 'Rural Municipality','district' => 'Parsa','state' => '2'),
  array('id' => '378','municipality' => 'Dhobini','type' => 'Rural Municipality','district' => 'Parsa','state' => '2'),
  array('id' => '379','municipality' => 'Chhipaharmai','type' => 'Rural Municipality','district' => 'Parsa','state' => '2'),
  array('id' => '380','municipality' => 'Pakaha Mainapur','type' => 'Rural Municipality','district' => 'Parsa','state' => '2'),
  array('id' => '381','municipality' => 'Bindabasini','type' => 'Rural Municipality','district' => 'Parsa','state' => '2'),
  array('id' => '382','municipality' => 'Sakhuwa Prasauni','type' => 'Rural Municipality','district' => 'Parsa','state' => '2'),
  array('id' => '383','municipality' => 'Paterwa Sugauli','type' => 'Rural Municipality','district' => 'Parsa','state' => '2'),
  array('id' => '384','municipality' => 'Kalikamai','type' => 'Rural Municipality','district' => 'Parsa','state' => '2'),
  array('id' => '385','municipality' => 'Jira Bhawani','type' => 'Rural Municipality','district' => 'Parsa','state' => '2'),
  array('id' => '386','municipality' => 'Bharatpur','type' => 'MetroPolitan City','district' => 'Chitwan','state' => '3'),
  array('id' => '387','municipality' => 'Kalika Chitwan','type' => 'Municipality','district' => 'Chitwan','state' => '3'),
  array('id' => '388','municipality' => 'Khairhani','type' => 'Municipality','district' => 'Chitwan','state' => '3'),
  array('id' => '389','municipality' => 'Madi Chitwan','type' => 'Municipality','district' => 'Chitwan','state' => '3'),
  array('id' => '390','municipality' => 'Ratnanagar','type' => 'Municipality','district' => 'Chitwan','state' => '3'),
  array('id' => '391','municipality' => 'Rapti Chitwan','type' => 'Municipality','district' => 'Chitwan','state' => '3'),
  array('id' => '392','municipality' => 'Echyakamana','type' => 'Rural Municipality','district' => 'Chitwan','state' => '3'),
  array('id' => '393','municipality' => 'Gorkha','type' => 'Municipality','district' => 'Gorkha','state' => '4'),
  array('id' => '394','municipality' => 'Palungtar','type' => 'Municipality','district' => 'Gorkha','state' => '4'),
  array('id' => '395','municipality' => 'Sulikot','type' => 'Rural Municipality','district' => 'Gorkha','state' => '4'),
  array('id' => '396','municipality' => 'Siranchok','type' => 'Rural Municipality','district' => 'Gorkha','state' => '4'),
  array('id' => '397','municipality' => 'Ajirkot','type' => 'Rural Municipality','district' => 'Gorkha','state' => '4'),
  array('id' => '398','municipality' => 'Aarughat','type' => 'Rural Municipality','district' => 'Gorkha','state' => '4'),
  array('id' => '399','municipality' => 'Gandaki','type' => 'Rural Municipality','district' => 'Gorkha','state' => '4'),
  array('id' => '400','municipality' => 'Chumnubri','type' => 'Rural Municipality','district' => 'Gorkha','state' => '4'),
  array('id' => '401','municipality' => 'Dharche','type' => 'Rural Municipality','district' => 'Gorkha','state' => '4'),
  array('id' => '402','municipality' => 'Bhimsen','type' => 'Rural Municipality','district' => 'Gorkha','state' => '4'),
  array('id' => '403','municipality' => 'Sahid Lakhan','type' => 'Rural Municipality','district' => 'Gorkha','state' => '4'),
  array('id' => '404','municipality' => 'Beshi Sahar','type' => 'Municipality','district' => 'Lamjung','state' => '4'),
  array('id' => '405','municipality' => 'Madhya Nepal','type' => 'Municipality','district' => 'Lamjung','state' => '4'),
  array('id' => '406','municipality' => 'Rainas','type' => 'Municipality','district' => 'Lamjung','state' => '4'),
  array('id' => '407','municipality' => 'Sundar Bajar','type' => 'Municipality','district' => 'Lamjung','state' => '4'),
  array('id' => '408','municipality' => 'Kobholasothar','type' => 'Rural Municipality','district' => 'Lamjung','state' => '4'),
  array('id' => '409','municipality' => 'Dudhpokhari','type' => 'Rural Municipality','district' => 'Lamjung','state' => '4'),
  array('id' => '410','municipality' => 'Dordi','type' => 'Rural Municipality','district' => 'Lamjung','state' => '4'),
  array('id' => '411','municipality' => 'Marsyandi','type' => 'Rural Municipality','district' => 'Lamjung','state' => '4'),
  array('id' => '412','municipality' => 'Bhanu','type' => 'Municipality','district' => 'Tanahun','state' => '4'),
  array('id' => '413','municipality' => 'Bhimad','type' => 'Municipality','district' => 'Tanahun','state' => '4'),
  array('id' => '414','municipality' => 'Byas','type' => 'Municipality','district' => 'Tanahun','state' => '4'),
  array('id' => '415','municipality' => 'Shuklagandaki','type' => 'Municipality','district' => 'Tanahun','state' => '4'),
  array('id' => '416','municipality' => 'Ambukhaireni','type' => 'Rural Municipality','district' => 'Tanahun','state' => '4'),
  array('id' => '417','municipality' => 'Rhishing','type' => 'Rural Municipality','district' => 'Tanahun','state' => '4'),
  array('id' => '418','municipality' => 'Ghiring','type' => 'Rural Municipality','district' => 'Tanahun','state' => '4'),
  array('id' => '419','municipality' => 'Devghat','type' => 'Rural Municipality','district' => 'Tanahun','state' => '4'),
  array('id' => '420','municipality' => 'Myagdi','type' => 'Rural Municipality','district' => 'Tanahun','state' => '4'),
  array('id' => '421','municipality' => 'Bandipur','type' => 'Rural Municipality','district' => 'Tanahun','state' => '4'),
  array('id' => '422','municipality' => 'Galyang','type' => 'Municipality','district' => 'Syangjha','state' => '4'),
  array('id' => '423','municipality' => 'Chapakot','type' => 'Municipality','district' => 'Syangjha','state' => '4'),
  array('id' => '424','municipality' => 'Putalibazar','type' => 'Municipality','district' => 'Syangjha','state' => '4'),
  array('id' => '425','municipality' => 'Virkot','type' => 'Municipality','district' => 'Syangjha','state' => '4'),
  array('id' => '426','municipality' => 'Waling','type' => 'Municipality','district' => 'Syangjha','state' => '4'),
  array('id' => '427','municipality' => 'Arjunchaupari','type' => 'Rural Municipality','district' => 'Syangjha','state' => '4'),
  array('id' => '428','municipality' => 'Aadhikhola','type' => 'Rural Municipality','district' => 'Syangjha','state' => '4'),
  array('id' => '429','municipality' => 'Kaligandaki Syangjha','type' => 'Rural Municipality','district' => 'Syangjha','state' => '4'),
  array('id' => '430','municipality' => 'Fedikhola','type' => 'Rural Municipality','district' => 'Syangjha','state' => '4'),
  array('id' => '431','municipality' => 'Biruwa','type' => 'Rural Municipality','district' => 'Syangjha','state' => '4'),
  array('id' => '432','municipality' => 'Harinas','type' => 'Rural Municipality','district' => 'Syangjha','state' => '4'),
  array('id' => '433','municipality' => 'Pokhara Lekhanath','type' => 'MetroPolitan City','district' => 'Kaski','state' => '4'),
  array('id' => '434','municipality' => 'Annapurna Kaski','type' => 'Rural Municipality','district' => 'Kaski','state' => '4'),
  array('id' => '435','municipality' => 'Machhapuchhre','type' => 'Rural Municipality','district' => 'Kaski','state' => '4'),
  array('id' => '436','municipality' => 'Madi Kaski','type' => 'Rural Municipality','district' => 'Kaski','state' => '4'),
  array('id' => '437','municipality' => 'Rupa','type' => 'Rural Municipality','district' => 'Kaski','state' => '4'),
  array('id' => '438','municipality' => 'Chame','type' => 'Rural Municipality','district' => 'Manang','state' => '4'),
  array('id' => '439','municipality' => 'Narfu','type' => 'Rural Municipality','district' => 'Manang','state' => '4'),
  array('id' => '440','municipality' => 'Nashon','type' => 'Rural Municipality','district' => 'Manang','state' => '4'),
  array('id' => '441','municipality' => 'Neshyang','type' => 'Rural Municipality','district' => 'Manang','state' => '4'),
  array('id' => '442','municipality' => 'Gharpajhong','type' => 'Rural Municipality','district' => 'Mustang','state' => '4'),
  array('id' => '443','municipality' => 'Thasang','type' => 'Rural Municipality','district' => 'Mustang','state' => '4'),
  array('id' => '444','municipality' => 'Dalome','type' => 'Rural Municipality','district' => 'Mustang','state' => '4'),
  array('id' => '445','municipality' => 'Lomanthang','type' => 'Rural Municipality','district' => 'Mustang','state' => '4'),
  array('id' => '446','municipality' => 'Barhagaun Muktichhetra','type' => 'Rural Municipality','district' => 'Mustang','state' => '4'),
  array('id' => '447','municipality' => 'Beni','type' => 'Municipality','district' => 'Myagdi','state' => '4'),
  array('id' => '448','municipality' => 'Annapurna Myagdi','type' => 'Rural Municipality','district' => 'Myagdi','state' => '4'),
  array('id' => '449','municipality' => 'Dhaulagiri','type' => 'Rural Municipality','district' => 'Myagdi','state' => '4'),
  array('id' => '450','municipality' => 'Mangala','type' => 'Rural Municipality','district' => 'Myagdi','state' => '4'),
  array('id' => '451','municipality' => 'Malika Myagdi','type' => 'Rural Municipality','district' => 'Myagdi','state' => '4'),
  array('id' => '452','municipality' => 'Raghuganga','type' => 'Rural Municipality','district' => 'Myagdi','state' => '4'),
  array('id' => '453','municipality' => 'Kushma','type' => 'Municipality','district' => 'Parbat','state' => '4'),
  array('id' => '454','municipality' => 'Phalewas','type' => 'Municipality','district' => 'Parbat','state' => '4'),
  array('id' => '455','municipality' => 'Jaljala','type' => 'Rural Municipality','district' => 'Parbat','state' => '4'),
  array('id' => '456','municipality' => 'paiyu','type' => 'Rural Municipality','district' => 'Parbat','state' => '4'),
  array('id' => '457','municipality' => 'Mahashila','type' => 'Rural Municipality','district' => 'Parbat','state' => '4'),
  array('id' => '458','municipality' => 'Modi','type' => 'Rural Municipality','district' => 'Parbat','state' => '4'),
  array('id' => '459','municipality' => 'Bihadi','type' => 'Rural Municipality','district' => 'Parbat','state' => '4'),
  array('id' => '460','municipality' => 'Baglung','type' => 'Municipality','district' => 'Baglung','state' => '4'),
  array('id' => '461','municipality' => 'Galkot','type' => 'Municipality','district' => 'Baglung','state' => '4'),
  array('id' => '462','municipality' => 'Jaimini','type' => 'Municipality','district' => 'Baglung','state' => '4'),
  array('id' => '463','municipality' => 'Dhorpatan','type' => 'Municipality','district' => 'Baglung','state' => '4'),
  array('id' => '464','municipality' => 'Bareng','type' => 'Rural Municipality','district' => 'Baglung','state' => '4'),
  array('id' => '465','municipality' => 'Kathekhola','type' => 'Rural Municipality','district' => 'Baglung','state' => '4'),
  array('id' => '466','municipality' => 'Tamankhola','type' => 'Rural Municipality','district' => 'Baglung','state' => '4'),
  array('id' => '467','municipality' => 'Tarakhola','type' => 'Rural Municipality','district' => 'Baglung','state' => '4'),
  array('id' => '468','municipality' => 'Nisikhola','type' => 'Rural Municipality','district' => 'Baglung','state' => '4'),
  array('id' => '469','municipality' => 'Badigad','type' => 'Rural Municipality','district' => 'Baglung','state' => '4'),
  array('id' => '470','municipality' => 'Musikot Gulmi','type' => 'Municipality','district' => 'Gulmi','state' => '5'),
  array('id' => '471','municipality' => 'Resunga','type' => 'Municipality','district' => 'Gulmi','state' => '5'),
  array('id' => '472','municipality' => 'Ishma','type' => 'Rural Municipality','district' => 'Gulmi','state' => '5'),
  array('id' => '473','municipality' => 'Kaligandaki Gulmi','type' => 'Rural Municipality','district' => 'Gulmi','state' => '5'),
  array('id' => '474','municipality' => 'Gulmidarbar','type' => 'Rural Municipality','district' => 'Gulmi','state' => '5'),
  array('id' => '475','municipality' => 'Satyawoti','type' => 'Rural Municipality','district' => 'Gulmi','state' => '5'),
  array('id' => '476','municipality' => 'Chandrakot','type' => 'Rural Municipality','district' => 'Gulmi','state' => '5'),
  array('id' => '477','municipality' => 'Ruru','type' => 'Rural Municipality','district' => 'Gulmi','state' => '5'),
  array('id' => '478','municipality' => 'Chhatrakot','type' => 'Rural Municipality','district' => 'Gulmi','state' => '5'),
  array('id' => '479','municipality' => 'Dhurkot','type' => 'Rural Municipality','district' => 'Gulmi','state' => '5'),
  array('id' => '480','municipality' => 'Madane','type' => 'Rural Municipality','district' => 'Gulmi','state' => '5'),
  array('id' => '481','municipality' => 'Malika Gulmi','type' => 'Rural Municipality','district' => 'Gulmi','state' => '5'),
  array('id' => '482','municipality' => 'Rampur','type' => 'Municipality','district' => 'Palpa','state' => '5'),
  array('id' => '483','municipality' => 'Tansen','type' => 'Municipality','district' => 'Palpa','state' => '5'),
  array('id' => '484','municipality' => 'Nisdi','type' => 'Rural Municipality','district' => 'Palpa','state' => '5'),
  array('id' => '485','municipality' => 'Purbakhola','type' => 'Rural Municipality','district' => 'Palpa','state' => '5'),
  array('id' => '486','municipality' => 'Rambha','type' => 'Rural Municipality','district' => 'Palpa','state' => '5'),
  array('id' => '487','municipality' => 'Mathagadi','type' => 'Rural Municipality','district' => 'Palpa','state' => '5'),
  array('id' => '488','municipality' => 'Tinau','type' => 'Rural Municipality','district' => 'Palpa','state' => '5'),
  array('id' => '489','municipality' => 'Baganaskali','type' => 'Rural Municipality','district' => 'Palpa','state' => '5'),
  array('id' => '490','municipality' => 'Ribdikot','type' => 'Rural Municipality','district' => 'Palpa','state' => '5'),
  array('id' => '491','municipality' => 'Rainadevi Chhahara','type' => 'Rural Municipality','district' => 'Palpa','state' => '5'),
  array('id' => '492','municipality' => 'Butwal','type' => 'Sub Metropolitan City','district' => 'Rupandehi','state' => '5'),
  array('id' => '493','municipality' => 'Debdaha','type' => 'Municipality','district' => 'Rupandehi','state' => '5'),
  array('id' => '494','municipality' => 'Lumbini Saskritik','type' => 'Municipality','district' => 'Rupandehi','state' => '5'),
  array('id' => '495','municipality' => 'Sainamaina','type' => 'Municipality','district' => 'Rupandehi','state' => '5'),
  array('id' => '496','municipality' => 'Sidharthanager','type' => 'Municipality','district' => 'Rupandehi','state' => '5'),
  array('id' => '497','municipality' => 'Tilottma','type' => 'Municipality','district' => 'Rupandehi','state' => '5'),
  array('id' => '498','municipality' => 'Gaidahawa','type' => 'Rural Municipality','district' => 'Rupandehi','state' => '5'),
  array('id' => '499','municipality' => 'Kanchan','type' => 'Rural Municipality','district' => 'Rupandehi','state' => '5'),
  array('id' => '500','municipality' => 'Kotahimai','type' => 'Rural Municipality','district' => 'Rupandehi','state' => '5'),
  array('id' => '501','municipality' => 'Marchawari','type' => 'Rural Municipality','district' => 'Rupandehi','state' => '5'),
  array('id' => '502','municipality' => 'Mayadevi Rupandehi','type' => 'Rural Municipality','district' => 'Rupandehi','state' => '5'),
  array('id' => '503','municipality' => 'Omsatiya','type' => 'Rural Municipality','district' => 'Rupandehi','state' => '5'),
  array('id' => '504','municipality' => 'Rohindi','type' => 'Rural Municipality','district' => 'Rupandehi','state' => '5'),
  array('id' => '505','municipality' => 'Sammarimai','type' => 'Rural Municipality','district' => 'Rupandehi','state' => '5'),
  array('id' => '506','municipality' => 'Siyari','type' => 'Rural Municipality','district' => 'Rupandehi','state' => '5'),
  array('id' => '507','municipality' => 'Suddodhan','type' => 'Rural Municipality','district' => 'Rupandehi','state' => '5'),
  array('id' => '508','municipality' => 'Kapilbastu','type' => 'Municipality','district' => 'Kapilbastu','state' => '5'),
  array('id' => '509','municipality' => 'Buddhabhumi','type' => 'Municipality','district' => 'Kapilbastu','state' => '5'),
  array('id' => '510','municipality' => 'Shivaraj','type' => 'Municipality','district' => 'Kapilbastu','state' => '5'),
  array('id' => '511','municipality' => 'Maharajgunj','type' => 'Municipality','district' => 'Kapilbastu','state' => '5'),
  array('id' => '512','municipality' => 'Krishnanagar','type' => 'Municipality','district' => 'Kapilbastu','state' => '5'),
  array('id' => '513','municipality' => 'Bandganga','type' => 'Municipality','district' => 'Kapilbastu','state' => '5'),
  array('id' => '514','municipality' => 'Mayadevi Kapilbastu','type' => 'Rural Municipality','district' => 'Kapilbastu','state' => '5'),
  array('id' => '515','municipality' => 'Yesodhara','type' => 'Rural Municipality','district' => 'Kapilbastu','state' => '5'),
  array('id' => '516','municipality' => 'Suddhodhan','type' => 'Rural Municipality','district' => 'Kapilbastu','state' => '5'),
  array('id' => '517','municipality' => 'Bijayanagar','type' => 'Rural Municipality','district' => 'Kapilbastu','state' => '5'),
  array('id' => '518','municipality' => 'Sandhikharka','type' => 'Municipality','district' => 'Arghakhachi','state' => '5'),
  array('id' => '519','municipality' => 'Sitganga','type' => 'Municipality','district' => 'Arghakhachi','state' => '5'),
  array('id' => '520','municipality' => 'Bhumikasthan','type' => 'Municipality','district' => 'Arghakhachi','state' => '5'),
  array('id' => '521','municipality' => 'Chhatradev','type' => 'Rural Municipality','district' => 'Arghakhachi','state' => '5'),
  array('id' => '522','municipality' => 'Pandini','type' => 'Rural Municipality','district' => 'Arghakhachi','state' => '5'),
  array('id' => '523','municipality' => 'Malarani','type' => 'Rural Municipality','district' => 'Arghakhachi','state' => '5'),
  array('id' => '524','municipality' => 'Pyuthan','type' => 'Municipality','district' => 'Pyuthan','state' => '5'),
  array('id' => '525','municipality' => 'Sworgadwari','type' => 'Municipality','district' => 'Pyuthan','state' => '5'),
  array('id' => '526','municipality' => 'Gaumukhi','type' => 'Rural Municipality','district' => 'Pyuthan','state' => '5'),
  array('id' => '527','municipality' => 'Mandabi','type' => 'Rural Municipality','district' => 'Pyuthan','state' => '5'),
  array('id' => '528','municipality' => 'Sarumarani','type' => 'Rural Municipality','district' => 'Pyuthan','state' => '5'),
  array('id' => '529','municipality' => 'Mallarani','type' => 'Rural Municipality','district' => 'Pyuthan','state' => '5'),
  array('id' => '530','municipality' => 'Naubahini','type' => 'Rural Municipality','district' => 'Pyuthan','state' => '5'),
  array('id' => '531','municipality' => 'Jhimruk','type' => 'Rural Municipality','district' => 'Pyuthan','state' => '5'),
  array('id' => '532','municipality' => 'Arawoti','type' => 'Rural Municipality','district' => 'Pyuthan','state' => '5'),
  array('id' => '533','municipality' => 'Rolpa','type' => 'Municipality','district' => 'Rolpa','state' => '5'),
  array('id' => '534','municipality' => 'Tribeni Rolpa','type' => 'Rural Municipality','district' => 'Rolpa','state' => '5'),
  array('id' => '535','municipality' => 'Duikholi','type' => 'Rural Municipality','district' => 'Rolpa','state' => '5'),
  array('id' => '536','municipality' => 'Madi Rolpa','type' => 'Rural Municipality','district' => 'Rolpa','state' => '5'),
  array('id' => '537','municipality' => 'Runtigadhi','type' => 'Rural Municipality','district' => 'Rolpa','state' => '5'),
  array('id' => '538','municipality' => 'Lungri','type' => 'Rural Municipality','district' => 'Rolpa','state' => '5'),
  array('id' => '539','municipality' => 'Sukidaha','type' => 'Rural Municipality','district' => 'Rolpa','state' => '5'),
  array('id' => '540','municipality' => 'Sunchhahari','type' => 'Rural Municipality','district' => 'Rolpa','state' => '5'),
  array('id' => '541','municipality' => 'Subarnawoti','type' => 'Rural Municipality','district' => 'Rolpa','state' => '5'),
  array('id' => '542','municipality' => 'Thabang','type' => 'Rural Municipality','district' => 'Rolpa','state' => '5'),
  array('id' => '543','municipality' => 'Musikot Rukum West','type' => 'Municipality','district' => 'Rukum West','state' => '6'),
  array('id' => '544','municipality' => 'Chaurjahari','type' => 'Municipality','district' => 'Rukum West','state' => '6'),
  array('id' => '545','municipality' => 'Aathabiskot','type' => 'Municipality','district' => 'Rukum West','state' => '6'),
  array('id' => '546','municipality' => 'Putha Uttarganga','type' => 'Rural Municipality','district' => 'Rukum East','state' => '5'),
  array('id' => '547','municipality' => 'Bhume','type' => 'Rural Municipality','district' => 'Rukum East','state' => '5'),
  array('id' => '548','municipality' => 'Sisne','type' => 'Rural Municipality','district' => 'Rukum East','state' => '5'),
  array('id' => '549','municipality' => 'Baphikot','type' => 'Rural Municipality','district' => 'Rukum West','state' => '6'),
  array('id' => '550','municipality' => 'Tribeni Rukum West','type' => 'Rural Municipality','district' => 'Rukum West','state' => '6'),
  array('id' => '551','municipality' => 'Sanibheri','type' => 'Rural Municipality','district' => 'Rukum West','state' => '6'),
  array('id' => '552','municipality' => 'Sarada','type' => 'Municipality','district' => 'Salyan','state' => '6'),
  array('id' => '553','municipality' => 'Bagchaur','type' => 'Municipality','district' => 'Salyan','state' => '6'),
  array('id' => '554','municipality' => 'Bangad','type' => 'Municipality','district' => 'Salyan','state' => '6'),
  array('id' => '555','municipality' => 'Kalimati','type' => 'Rural Municipality','district' => 'Salyan','state' => '6'),
  array('id' => '556','municipality' => 'Tribeni Salyan','type' => 'Rural Municipality','district' => 'Salyan','state' => '6'),
  array('id' => '557','municipality' => 'Kapurkot','type' => 'Rural Municipality','district' => 'Salyan','state' => '6'),
  array('id' => '558','municipality' => 'Chhatreswori','type' => 'Rural Municipality','district' => 'Salyan','state' => '6'),
  array('id' => '559','municipality' => 'Dhorchaur','type' => 'Rural Municipality','district' => 'Salyan','state' => '6'),
  array('id' => '560','municipality' => 'Kumakhamalika','type' => 'Rural Municipality','district' => 'Salyan','state' => '6'),
  array('id' => '561','municipality' => 'Darma','type' => 'Rural Municipality','district' => 'Salyan','state' => '6'),
  array('id' => '562','municipality' => 'Tulsipur','type' => 'Sub Metropolitan City','district' => 'Dang','state' => '5'),
  array('id' => '563','municipality' => 'Ghorahi','type' => 'Sub Metropolitan City','district' => 'Dang','state' => '5'),
  array('id' => '564','municipality' => 'Lamahi','type' => 'Municipality','district' => 'Dang','state' => '5'),
  array('id' => '565','municipality' => 'Bangalichuli','type' => 'Rural Municipality','district' => 'Dang','state' => '5'),
  array('id' => '566','municipality' => 'Dangisaran','type' => 'Rural Municipality','district' => 'Dang','state' => '5'),
  array('id' => '567','municipality' => 'Gadhawa','type' => 'Rural Municipality','district' => 'Dang','state' => '5'),
  array('id' => '568','municipality' => 'Rajpur Dang','type' => 'Rural Municipality','district' => 'Dang','state' => '5'),
  array('id' => '569','municipality' => 'Rapti Dang','type' => 'Rural Municipality','district' => 'Dang','state' => '5'),
  array('id' => '570','municipality' => 'Santinagar','type' => 'Rural Municipality','district' => 'Dang','state' => '5'),
  array('id' => '571','municipality' => 'Babai','type' => 'Rural Municipality','district' => 'Dang','state' => '5'),
  array('id' => '572','municipality' => 'Nepalgunj','type' => 'Sub Metropolitan City','district' => 'Banke','state' => '5'),
  array('id' => '573','municipality' => 'Koholpur','type' => 'Municipality','district' => 'Banke','state' => '5'),
  array('id' => '574','municipality' => 'Narainapur','type' => 'Rural Municipality','district' => 'Banke','state' => '5'),
  array('id' => '575','municipality' => 'Raptisonari','type' => 'Rural Municipality','district' => 'Banke','state' => '5'),
  array('id' => '576','municipality' => 'Baijanath','type' => 'Rural Municipality','district' => 'Banke','state' => '5'),
  array('id' => '577','municipality' => 'Khajura','type' => 'Rural Municipality','district' => 'Banke','state' => '5'),
  array('id' => '578','municipality' => 'Duduwa','type' => 'Rural Municipality','district' => 'Banke','state' => '5'),
  array('id' => '579','municipality' => 'Janaki Banke','type' => 'Rural Municipality','district' => 'Banke','state' => '5'),
  array('id' => '580','municipality' => 'Gulariya','type' => 'Municipality','district' => 'Bardiya','state' => '5'),
  array('id' => '581','municipality' => 'Madhuban','type' => 'Municipality','district' => 'Bardiya','state' => '5'),
  array('id' => '582','municipality' => 'Rajapur','type' => 'Municipality','district' => 'Bardiya','state' => '5'),
  array('id' => '583','municipality' => 'Thakurbaba','type' => 'Municipality','district' => 'Bardiya','state' => '5'),
  array('id' => '584','municipality' => 'Bansgadhi','type' => 'Municipality','district' => 'Bardiya','state' => '5'),
  array('id' => '585','municipality' => 'Barbardiya','type' => 'Municipality','district' => 'Bardiya','state' => '5'),
  array('id' => '586','municipality' => 'Badhaiyatal','type' => 'Rural Municipality','district' => 'Bardiya','state' => '5'),
  array('id' => '587','municipality' => 'Geruwa','type' => 'Rural Municipality','district' => 'Bardiya','state' => '5'),
  array('id' => '588','municipality' => 'Birendranagar','type' => 'Municipality','district' => 'Surkhet','state' => '6'),
  array('id' => '589','municipality' => 'Bheriganga','type' => 'Municipality','district' => 'Surkhet','state' => '6'),
  array('id' => '590','municipality' => 'Gurbhakot','type' => 'Municipality','district' => 'Surkhet','state' => '6'),
  array('id' => '591','municipality' => 'Pabchapuri','type' => 'Municipality','district' => 'Surkhet','state' => '6'),
  array('id' => '592','municipality' => 'Lekbesi','type' => 'Municipality','district' => 'Surkhet','state' => '6'),
  array('id' => '593','municipality' => 'Chaukune','type' => 'Rural Municipality','district' => 'Surkhet','state' => '6'),
  array('id' => '594','municipality' => 'Barahatal','type' => 'Rural Municipality','district' => 'Surkhet','state' => '6'),
  array('id' => '595','municipality' => 'Chingad','type' => 'Rural Municipality','district' => 'Surkhet','state' => '6'),
  array('id' => '596','municipality' => 'Simta','type' => 'Rural Municipality','district' => 'Surkhet','state' => '6'),
  array('id' => '597','municipality' => 'Narayan','type' => 'Municipality','district' => 'Dailekh','state' => '6'),
  array('id' => '598','municipality' => 'Dullu','type' => 'Municipality','district' => 'Dailekh','state' => '6'),
  array('id' => '599','municipality' => 'Chamunda Bindrasaini','type' => 'Municipality','district' => 'Dailekh','state' => '6'),
  array('id' => '600','municipality' => 'Aathbis','type' => 'Municipality','district' => 'Dailekh','state' => '6'),
  array('id' => '601','municipality' => 'Bhagawatimai','type' => 'Rural Municipality','district' => 'Dailekh','state' => '6'),
  array('id' => '602','municipality' => 'Gurash','type' => 'Rural Municipality','district' => 'Dailekh','state' => '6'),
  array('id' => '603','municipality' => 'Dungeshwar','type' => 'Rural Municipality','district' => 'Dailekh','state' => '6'),
  array('id' => '604','municipality' => 'Naumule','type' => 'Rural Municipality','district' => 'Dailekh','state' => '6'),
  array('id' => '605','municipality' => 'Mahabu','type' => 'Rural Municipality','district' => 'Dailekh','state' => '6'),
  array('id' => '606','municipality' => 'Bhairabi','type' => 'Rural Municipality','district' => 'Dailekh','state' => '6'),
  array('id' => '607','municipality' => 'Thatikadh','type' => 'Rural Municipality','district' => 'Dailekh','state' => '6'),
  array('id' => '608','municipality' => 'Beri','type' => 'Municipality','district' => 'Jajarkot','state' => '6'),
  array('id' => '609','municipality' => 'Chhedagad','type' => 'Municipality','district' => 'Jajarkot','state' => '6'),
  array('id' => '610','municipality' => 'Tribeni nalgad','type' => 'Municipality','district' => 'Jajarkot','state' => '6'),
  array('id' => '611','municipality' => 'Barekot','type' => 'Rural Municipality','district' => 'Jajarkot','state' => '6'),
  array('id' => '612','municipality' => 'Kuse','type' => 'Rural Municipality','district' => 'Jajarkot','state' => '6'),
  array('id' => '613','municipality' => 'Junichande','type' => 'Rural Municipality','district' => 'Jajarkot','state' => '6'),
  array('id' => '614','municipality' => 'Shibalaya','type' => 'Rural Municipality','district' => 'Jajarkot','state' => '6'),
  array('id' => '615','municipality' => 'Thuli veri','type' => 'Municipality','district' => 'Dolpa','state' => '6'),
  array('id' => '616','municipality' => 'Tripurasundari Dolpa','type' => 'Municipality','district' => 'Dolpa','state' => '6'),
  array('id' => '617','municipality' => 'Dolpa buddha','type' => 'Rural Municipality','district' => 'Dolpa','state' => '6'),
  array('id' => '618','municipality' => 'She phoksundo','type' => 'Rural Municipality','district' => 'Dolpa','state' => '6'),
  array('id' => '619','municipality' => 'Jagdulla','type' => 'Rural Municipality','district' => 'Dolpa','state' => '6'),
  array('id' => '620','municipality' => 'Mudkechula','type' => 'Rural Municipality','district' => 'Dolpa','state' => '6'),
  array('id' => '621','municipality' => 'Kaike','type' => 'Rural Municipality','district' => 'Dolpa','state' => '6'),
  array('id' => '622','municipality' => 'Chharka tangsong','type' => 'Rural Municipality','district' => 'Dolpa','state' => '6'),
  array('id' => '623','municipality' => 'Chandannath','type' => 'Municipality','district' => 'Jumla','state' => '6'),
  array('id' => '624','municipality' => 'Kankasundari','type' => 'Rural Municipality','district' => 'Jumla','state' => '6'),
  array('id' => '625','municipality' => 'Sinja','type' => 'Rural Municipality','district' => 'Jumla','state' => '6'),
  array('id' => '626','municipality' => 'Hima','type' => 'Rural Municipality','district' => 'Jumla','state' => '6'),
  array('id' => '627','municipality' => 'Tila','type' => 'Rural Municipality','district' => 'Jumla','state' => '6'),
  array('id' => '628','municipality' => 'Guthichaur','type' => 'Rural Municipality','district' => 'Jumla','state' => '6'),
  array('id' => '629','municipality' => 'Tatopani','type' => 'Rural Municipality','district' => 'Jumla','state' => '6'),
  array('id' => '630','municipality' => 'Patarasi','type' => 'Rural Municipality','district' => 'Jumla','state' => '6'),
  array('id' => '631','municipality' => 'Khadachakra','type' => 'Municipality','district' => 'Kalikot','state' => '6'),
  array('id' => '632','municipality' => 'Raskot','type' => 'Municipality','district' => 'Kalikot','state' => '6'),
  array('id' => '633','municipality' => 'Tilagupha','type' => 'Municipality','district' => 'Kalikot','state' => '6'),
  array('id' => '634','municipality' => 'Pachaljharana','type' => 'Rural Municipality','district' => 'Kalikot','state' => '6'),
  array('id' => '635','municipality' => 'Sanni tribeni','type' => 'Rural Municipality','district' => 'Kalikot','state' => '6'),
  array('id' => '636','municipality' => 'Naraharinath','type' => 'Rural Municipality','district' => 'Kalikot','state' => '6'),
  array('id' => '637','municipality' => 'Kalika Kalikot','type' => 'Rural Municipality','district' => 'Kalikot','state' => '6'),
  array('id' => '638','municipality' => 'Mahabai','type' => 'Rural Municipality','district' => 'Kalikot','state' => '6'),
  array('id' => '639','municipality' => 'Palata','type' => 'Rural Municipality','district' => 'Kalikot','state' => '6'),
  array('id' => '640','municipality' => 'Chhayanath Rara','type' => 'Municipality','district' => 'Mugu','state' => '6'),
  array('id' => '641','municipality' => 'Mugumkarmarog','type' => 'Rural Municipality','district' => 'Mugu','state' => '6'),
  array('id' => '642','municipality' => 'Soru','type' => 'Rural Municipality','district' => 'Mugu','state' => '6'),
  array('id' => '643','municipality' => 'Khatyad','type' => 'Rural Municipality','district' => 'Mugu','state' => '6'),
  array('id' => '644','municipality' => 'Simkot','type' => 'Rural Municipality','district' => 'Humla','state' => '6'),
  array('id' => '645','municipality' => 'Namkha','type' => 'Rural Municipality','district' => 'Humla','state' => '6'),
  array('id' => '646','municipality' => 'kharpunath','type' => 'Rural Municipality','district' => 'Humla','state' => '6'),
  array('id' => '647','municipality' => 'Surkegad','type' => 'Rural Municipality','district' => 'Humla','state' => '6'),
  array('id' => '648','municipality' => 'Chankheli','type' => 'Rural Municipality','district' => 'Humla','state' => '6'),
  array('id' => '649','municipality' => 'Adanchuli','type' => 'Rural Municipality','district' => 'Humla','state' => '6'),
  array('id' => '650','municipality' => 'Tajakot','type' => 'Rural Municipality','district' => 'Humla','state' => '6'),
  array('id' => '651','municipality' => 'Badimalika','type' => 'Municipality','district' => 'Bajura','state' => '7'),
  array('id' => '652','municipality' => 'Tribeni Bajura','type' => 'Municipality','district' => 'Bajura','state' => '7'),
  array('id' => '653','municipality' => 'Budhiganga Bajura','type' => 'Municipality','district' => 'Bajura','state' => '7'),
  array('id' => '654','municipality' => 'Budhinanda','type' => 'Municipality','district' => 'Bajura','state' => '7'),
  array('id' => '655','municipality' => 'Gaumul','type' => 'Rural Municipality','district' => 'Bajura','state' => '7'),
  array('id' => '656','municipality' => 'Pandav Gufa','type' => 'Rural Municipality','district' => 'Bajura','state' => '7'),
  array('id' => '657','municipality' => 'Swamikartik','type' => 'Rural Municipality','district' => 'Bajura','state' => '7'),
  array('id' => '658','municipality' => 'Chhededaha','type' => 'Rural Municipality','district' => 'Bajura','state' => '7'),
  array('id' => '659','municipality' => 'Himali','type' => 'Rural Municipality','district' => 'Bajura','state' => '7'),
  array('id' => '660','municipality' => 'jayaprithvi','type' => 'Municipality','district' => 'Bajhang','state' => '7'),
  array('id' => '661','municipality' => 'Bungal','type' => 'Municipality','district' => 'Bajhang','state' => '7'),
  array('id' => '662','municipality' => 'Talkot','type' => 'Rural Municipality','district' => 'Bajhang','state' => '7'),
  array('id' => '663','municipality' => 'Masta','type' => 'Rural Municipality','district' => 'Bajhang','state' => '7'),
  array('id' => '664','municipality' => 'Khaptadchhanna','type' => 'Rural Municipality','district' => 'Bajhang','state' => '7'),
  array('id' => '665','municipality' => 'Thalara','type' => 'Rural Municipality','district' => 'Bajhang','state' => '7'),
  array('id' => '666','municipality' => 'Bitthadchir','type' => 'Rural Municipality','district' => 'Bajhang','state' => '7'),
  array('id' => '667','municipality' => 'Surma','type' => 'Rural Municipality','district' => 'Bajhang','state' => '7'),
  array('id' => '668','municipality' => 'Chhabispathibhera','type' => 'Rural Municipality','district' => 'Bajhang','state' => '7'),
  array('id' => '669','municipality' => 'Durgathali','type' => 'Rural Municipality','district' => 'Bajhang','state' => '7'),
  array('id' => '670','municipality' => 'Kedarsyun','type' => 'Rural Municipality','district' => 'Bajhang','state' => '7'),
  array('id' => '671','municipality' => 'Kanda','type' => 'Rural Municipality','district' => 'Bajhang','state' => '7'),
  array('id' => '672','municipality' => 'Mangalsen','type' => 'Municipality','district' => 'Achham','state' => '7'),
  array('id' => '673','municipality' => 'Kamalbajar','type' => 'Municipality','district' => 'Achham','state' => '7'),
  array('id' => '674','municipality' => 'Sanphebagar','type' => 'Municipality','district' => 'Achham','state' => '7'),
  array('id' => '675','municipality' => 'Panchadewal Binayak','type' => 'Municipality','district' => 'Achham','state' => '7'),
  array('id' => '676','municipality' => 'Chaurpati','type' => 'Rural Municipality','district' => 'Achham','state' => '7'),
  array('id' => '677','municipality' => 'Mellekh','type' => 'Rural Municipality','district' => 'Achham','state' => '7'),
  array('id' => '678','municipality' => 'Bannigadi Jayagadh','type' => 'Rural Municipality','district' => 'Achham','state' => '7'),
  array('id' => '679','municipality' => 'Ramaroshan','type' => 'Rural Municipality','district' => 'Achham','state' => '7'),
  array('id' => '680','municipality' => 'Dhakari','type' => 'Rural Municipality','district' => 'Achham','state' => '7'),
  array('id' => '681','municipality' => 'Turmakhad','type' => 'Rural Municipality','district' => 'Achham','state' => '7'),
  array('id' => '682','municipality' => 'Dipayal siladhi','type' => 'Municipality','district' => 'Doti','state' => '7'),
  array('id' => '683','municipality' => 'Shikhar','type' => 'Municipality','district' => 'Doti','state' => '7'),
  array('id' => '684','municipality' => 'Purbichauki','type' => 'Rural Municipality','district' => 'Doti','state' => '7'),
  array('id' => '685','municipality' => 'Badikedar','type' => 'Rural Municipality','district' => 'Doti','state' => '7'),
  array('id' => '686','municipality' => 'Jorayal','type' => 'Rural Municipality','district' => 'Doti','state' => '7'),
  array('id' => '687','municipality' => 'Sayal','type' => 'Rural Municipality','district' => 'Doti','state' => '7'),
  array('id' => '688','municipality' => 'Aadarsh','type' => 'Rural Municipality','district' => 'Doti','state' => '7'),
  array('id' => '689','municipality' => 'K.I.C','type' => 'Rural Municipality','district' => 'Doti','state' => '7'),
  array('id' => '690','municipality' => 'Bogatan','type' => 'Rural Municipality','district' => 'Doti','state' => '7'),
  array('id' => '691','municipality' => 'Dhangadhi','type' => 'Sub Metropolitan City','district' => 'Kailali','state' => '7'),
  array('id' => '692','municipality' => 'Tikapur','type' => 'Municipality','district' => 'Kailali','state' => '7'),
  array('id' => '693','municipality' => 'Ghodaghodi','type' => 'Municipality','district' => 'Kailali','state' => '7'),
  array('id' => '694','municipality' => 'Lamkichuha','type' => 'Municipality','district' => 'Kailali','state' => '7'),
  array('id' => '695','municipality' => 'bhajani','type' => 'Municipality','district' => 'Kailali','state' => '7'),
  array('id' => '696','municipality' => 'Godawari Kailali','type' => 'Municipality','district' => 'Kailali','state' => '7'),
  array('id' => '697','municipality' => 'Gauriganga','type' => 'Municipality','district' => 'Kailali','state' => '7'),
  array('id' => '698','municipality' => 'Janaki Kailali','type' => 'Rural Municipality','district' => 'Kailali','state' => '7'),
  array('id' => '699','municipality' => 'Bardagoriya','type' => 'Rural Municipality','district' => 'Kailali','state' => '7'),
  array('id' => '700','municipality' => 'Mohanyal','type' => 'Rural Municipality','district' => 'Kailali','state' => '7'),
  array('id' => '701','municipality' => 'Kailari','type' => 'Rural Municipality','district' => 'Kailali','state' => '7'),
  array('id' => '702','municipality' => 'Joshipur','type' => 'Rural Municipality','district' => 'Kailali','state' => '7'),
  array('id' => '703','municipality' => 'Chure','type' => 'Rural Municipality','district' => 'Kailali','state' => '7'),
  array('id' => '704','municipality' => 'bhimdatta','type' => 'Municipality','district' => 'Kanchanpur','state' => '7'),
  array('id' => '705','municipality' => 'Punarbas','type' => 'Municipality','district' => 'Kanchanpur','state' => '7'),
  array('id' => '706','municipality' => 'Bedkot','type' => 'Municipality','district' => 'Kanchanpur','state' => '7'),
  array('id' => '707','municipality' => 'Mahakali Kanchanpur','type' => 'Municipality','district' => 'Kanchanpur','state' => '7'),
  array('id' => '708','municipality' => 'Shuklaphata','type' => 'Municipality','district' => 'Kanchanpur','state' => '7'),
  array('id' => '709','municipality' => 'Belauri','type' => 'Municipality','district' => 'Kanchanpur','state' => '7'),
  array('id' => '710','municipality' => 'Krishnapur','type' => 'Municipality','district' => 'Kanchanpur','state' => '7'),
  array('id' => '711','municipality' => 'Beldandi','type' => 'Rural Municipality','district' => 'Kanchanpur','state' => '7'),
  array('id' => '712','municipality' => 'Laljhadi','type' => 'Rural Municipality','district' => 'Kanchanpur','state' => '7'),
  array('id' => '713','municipality' => 'Amargadhi','type' => 'Municipality','district' => 'Dadeldhura','state' => '7'),
  array('id' => '714','municipality' => 'Parsuram','type' => 'Municipality','district' => 'Dadeldhura','state' => '7'),
  array('id' => '715','municipality' => 'Aalital','type' => 'Rural Municipality','district' => 'Dadeldhura','state' => '7'),
  array('id' => '716','municipality' => 'Bhageshwar','type' => 'Rural Municipality','district' => 'Dadeldhura','state' => '7'),
  array('id' => '717','municipality' => 'nabadurga','type' => 'Rural Municipality','district' => 'Dadeldhura','state' => '7'),
  array('id' => '718','municipality' => 'Ajayameru','type' => 'Rural Municipality','district' => 'Dadeldhura','state' => '7'),
  array('id' => '719','municipality' => 'Ganyapdhura','type' => 'Rural Municipality','district' => 'Dadeldhura','state' => '7'),
  array('id' => '720','municipality' => 'Dashrathachanda','type' => 'Municipality','district' => 'Baitadi','state' => '7'),
  array('id' => '721','municipality' => 'Patan','type' => 'Municipality','district' => 'Baitadi','state' => '7'),
  array('id' => '722','municipality' => 'Melauli','type' => 'Municipality','district' => 'Baitadi','state' => '7'),
  array('id' => '723','municipality' => 'Purchaudi','type' => 'Municipality','district' => 'Baitadi','state' => '7'),
  array('id' => '724','municipality' => 'Surnaya','type' => 'Rural Municipality','district' => 'Baitadi','state' => '7'),
  array('id' => '725','municipality' => 'Sisag','type' => 'Rural Municipality','district' => 'Baitadi','state' => '7'),
  array('id' => '726','municipality' => 'Shivanath','type' => 'Rural Municipality','district' => 'Baitadi','state' => '7'),
  array('id' => '727','municipality' => 'Pancheshwar','type' => 'Rural Municipality','district' => 'Baitadi','state' => '7'),
  array('id' => '728','municipality' => 'Dogdakedar','type' => 'Rural Municipality','district' => 'Baitadi','state' => '7'),
  array('id' => '729','municipality' => 'Dilasaini','type' => 'Rural Municipality','district' => 'Baitadi','state' => '7'),
  array('id' => '730','municipality' => 'Mahakali Darchula','type' => 'Municipality','district' => 'Darchula','state' => '7'),
  array('id' => '731','municipality' => 'Shailyashikar','type' => 'Municipality','district' => 'Darchula','state' => '7'),
  array('id' => '732','municipality' => 'Malikarjun','type' => 'Rural Municipality','district' => 'Darchula','state' => '7'),
  array('id' => '733','municipality' => 'Apihimal','type' => 'Rural Municipality','district' => 'Darchula','state' => '7'),
  array('id' => '734','municipality' => 'Duhu','type' => 'Rural Municipality','district' => 'Darchula','state' => '7'),
  array('id' => '735','municipality' => 'Naugad','type' => 'Rural Municipality','district' => 'Darchula','state' => '7'),
  array('id' => '736','municipality' => 'Marma','type' => 'Rural Municipality','district' => 'Darchula','state' => '7'),
  array('id' => '737','municipality' => 'Lekam','type' => 'Rural Municipality','district' => 'Darchula','state' => '7'),
  array('id' => '738','municipality' => 'Byash','type' => 'Rural Municipality','district' => 'Darchula','state' => '7'),
  array('id' => '739','municipality' => 'Kawasoti','type' => 'Municipality','district' => 'Nawalparasi East','state' => '4'),
  array('id' => '740','municipality' => 'Gaindakot','type' => 'Municipality','district' => 'Nawalparasi East','state' => '4'),
  array('id' => '741','municipality' => 'Devchuli','type' => 'Municipality','district' => 'Nawalparasi East','state' => '4'),
  array('id' => '742','municipality' => 'Madhyabindu','type' => 'Municipality','district' => 'Nawalparasi East','state' => '4'),
  array('id' => '743','municipality' => 'Bungdikali','type' => 'Rural Municipality','district' => 'Nawalparasi East','state' => '4'),
  array('id' => '744','municipality' => 'Bulingtar','type' => 'Rural Municipality','district' => 'Nawalparasi East','state' => '4'),
  array('id' => '745','municipality' => 'Binaya Tribeni','type' => 'Rural Municipality','district' => 'Nawalparasi East','state' => '4'),
  array('id' => '746','municipality' => 'Hupsekot','type' => 'Rural Municipality','district' => 'Nawalparasi East','state' => '4'),
  array('id' => '747','municipality' => 'Bardghat','type' => 'Municipality','district' => 'Nawalparasi West','state' => '5'),
  array('id' => '748','municipality' => 'Ramgram','type' => 'Municipality','district' => 'Nawalparasi West','state' => '5'),
  array('id' => '749','municipality' => 'Sunwal','type' => 'Municipality','district' => 'Nawalparasi West','state' => '5'),
  array('id' => '750','municipality' => 'Susta','type' => 'Rural Municipality','district' => 'Nawalparasi West','state' => '5'),
  array('id' => '751','municipality' => 'Palhinandan','type' => 'Rural Municipality','district' => 'Nawalparasi West','state' => '5'),
  array('id' => '752','municipality' => 'Pratappur','type' => 'Rural Municipality','district' => 'Nawalparasi West','state' => '5'),
  array('id' => '753','municipality' => 'Sarawal','type' => 'Rural Municipality','district' => 'Nawalparasi West','state' => '5')
);
