<?php
return [
    [
        'part' => 'part-1',
        'part_name' => 'Data Verifications',
        'type' => 'a',
        'type_name' => 'Recounting reported Results:',
        'type_description' => 'Recount results from the periodic reports sent from the subnational units to the national level and compare to the value published by the National Program (or reported by the National Program to the Donor, if applicable).  Explain discrepancies (if any).',
        'sort_order' => 1,
        'status' => 1,
    ],
    [
        'part' => 'part-1',
        'part_name' => 'Data Verifications',
        'type' => 'b',
        'type_name' => 'Reporting Performance:',
        'type_description' => 'Review availability, completeness, and timeliness of reports from all subnational units.  How many reports should there have been from all subnational units?  How many are there?  Were they received on time? Are they complete?',
        'sort_order' => 2,
        'status' => 1,
    ],
    [
        'part' => 'part-1',
        'part_name' => 'Data Verifications',
        'type' => 'c',
        'type_name' => 'Cross check:',
        'type_description' => 'Cross check desc',
        'sub_type' => 'cross-check-1',
        'sub_type_name' => 'Cross check 1:',
        'sub_type_description' => 'Cross check 1 desc',
        'sort_order' => 3,
        'status' => 1,
    ],
    [
        'part' => 'part-1',
        'part_name' => 'Data Verifications',
        'type' => 'c',
        'type_name' => 'Cross check:',
        'type_description' => 'Cross check desc',
        'sub_type' => 'cross-check-2',
        'sub_type_name' => 'Cross check 2:',
        'sub_type_description' => 'Cross check 2 desc',
        'sort_order' => 4,
        'status' => 1,
    ],
    [
        'part' => 'part-1',
        'part_name' => 'Data Verifications',
        'type' => 'c',
        'type_name' => 'Cross check:',
        'type_description' => 'Cross check desc',
        'sub_type' => 'cross-check-3',
        'sub_type_name' => 'Cross check 3:',
        'sub_type_description' => 'Cross check 3 desc',
        'sort_order' => 5,
        'status' => 1,
    ],
    [
        'part' => 'part-2',
        'part_name' => 'System Assessment',
        'type' => '1',
        'type_name' => 'M&E Structure, Functions and Capabilities',
        'sort_order' => 6,
        'status' => 1,
    ],
    [
        'part' => 'part-2',
        'part_name' => 'System Assessment',
        'type' => '2',
        'type_name' => 'Indicator Definitions and Reporting Guidelines',
        'sort_order' => 7,
        'status' => 1,
    ],
    [
        'part' => 'part-2',
        'part_name' => 'System Assessment',
        'type' => '3',
        'type_name' => 'Data-collection and Reporting Forms and Tools',
        'sort_order' => 8,
        'status' => 1,
    ],

    [
        'part' => 'part-2',
        'part_name' => 'System Assessment',
        'type' => '4',
        'type_name' => 'Data Management Processes',
        'sort_order' => 9,
        'status' => 1,
    ],

    [
        'part' => 'part-2',
        'part_name' => 'System Assessment',
        'type' => '5',
        'type_name' => 'Link with the National System',
        'sort_order' => 10,
        'status' => 1,
    ],

    [
        'part' => 'part-2',
        'part_name' => 'System Assessment',
        'type' => '6',
        'type_name' => 'Use of Data for Decision Making	',
        'sort_order' => 11,
        'status' => 1,
    ],

    [
        'part' => 'part-3',
        'part_name' => 'Follow up Recommendations and Action Plan - National M&E Unit',
        'part_description' => 'Summarize key issues that the Program should follow up at various levels of the system (e.g. issues found at site level and/or at district/region level).',
        'type' => '1',
        'type_name' => 'Identified Weaknesses',
        'sort_order' => 12,
        'status' => 1,
    ],
    [
        'part' => 'part-3',
        'part_name' => 'Follow up Recommendations and Action Plan - National M&E Unit',
        'part_description' => 'Summarize key issues that the Program should follow up at various levels of the system (e.g. issues found at site level and/or at district/region level).',
        'type' => '2',
        'type_name' => 'Description of Action Point',
        'sort_order' => 13,
        'status' => 1,
    ],
    [
        'part' => 'part-3',
        'part_name' => 'Follow up Recommendations and Action Plan - National M&E Unit',
        'part_description' => 'Summarize key issues that the Program should follow up at various levels of the system (e.g. issues found at site level and/or at district/region level).',
        'type' => '3',
        'type_name' => 'Responsible(s)',
        'sort_order' => 14,
        'status' => 1,
    ],
    [
        'part' => 'part-3',
        'part_name' => 'Follow up Recommendations and Action Plan - National M&E Unit',
        'part_description' => 'Summarize key issues that the Program should follow up at various levels of the system (e.g. issues found at site level and/or at district/region level).',
        'type' => '4',
        'type_name' => 'Time Line',
        'sort_order' => 15,
        'status' => 1,
    ],


];